### ISSUE TITLE
腾讯云函数不能运行吗？

### ISSUE THREAD

**Issue by XiaYi1002** [lxk0301/scripts#1]
所需依赖都有安装了，但是运行不了，是什么问题呢

**Comment by XiaYi1002** [comment]
腾讯云函数

**Comment by lxk0301** [comment]
腾讯云函数我没有。所以没在上面测试过，pc上面nodejs是可以的。腾讯云函数是免费申请的吗？

**Comment by XiaYi1002** [comment]
> 腾讯云函数我没有。所以没在上面测试过，pc上面nodejs是可以的。腾讯云函数是免费申请的吗？

是的啊 免费的  现在这类脚本都是挂在腾讯云函数上面

**Comment by lxk0301** [comment]
我有空申请一个测试一下吧，&nbsp; 你可以考虑我redame里面致谢链接 的phyone脚本，&nbsp;https://github.com/Zero-S1/JD_tools




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lxk0301/scripts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月11日(星期二) 上午10:10
收件人:&nbsp;"lxk0301/scripts"<scripts@noreply.github.com&gt;;
抄送:&nbsp;"　被折叠的记忆"<778732665@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [lxk0301/scripts] 腾讯云函数不能运行吗？ (#1)





  
腾讯云函数我没有。所以没在上面测试过，pc上面nodejs是可以的。腾讯云函数是免费申请的吗？
  
是的啊 免费的  现在这类脚本都是挂在腾讯云函数上面

**Comment by lxk0301** [comment]
@XiaYi1002  我申请试了一下， 我也没跑成功， 不知什么原因。
 你可以看看这个 https://github.com/NobyDa/Script/issues/173 
使用安卓手机上面跑node.js

**Comment by XiaYi1002** [comment]
> @XiaYi1002 我申请试了一下， 我也没跑成功， 不知什么原因。
> 你可以看看这个 [NobyDa/Script#173](https://github.com/NobyDa/Script/issues/173)
> 使用安卓手机上面跑node.js

有空试试  感觉可以auto.js 这个软件也不错  然后cookies 单独一个txt  也方便更新吧

**Comment by lxk0301** [comment]
脚本不支持auto.js的语法。&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lxk0301/scripts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月11日(星期二) 下午2:59
收件人:&nbsp;"lxk0301/scripts"<scripts@noreply.github.com&gt;;
抄送:&nbsp;"　被折叠的记忆"<778732665@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [lxk0301/scripts] 腾讯云函数不能运行吗？ (#1)





  
@XiaYi1002 我申请试了一下， 我也没跑成功， 不知什么原因。
 你可以看看这个 NobyDa/Script#173
 使用安卓手机上面跑node.js
  
有空试试  感觉可以auto.js 这个软件也不错  然后cookies 单独一个txt  也方便更新吧

**Comment by mxzsw123456** [comment]
腾讯云和阿里云的函数试了都失败，只能在pc上手动了

**Comment by lxk0301** [comment]
@mxzsw123456  阿里云 可以考虑用这个  https://github.com/Zero-S1/JD_tools ,
作者有说 阿里云可以 https://github.com/Zero-S1/JD_tools/issues/15#issuecomment-671997226

**Comment by mxzsw123456** [comment]
> @mxzsw123456 阿里云 可以考虑用这个 https://github.com/Zero-S1/JD_tools ,
> 作者有说 阿里云可以 [Zero-S1/JD_tools#15 (comment)](https://github.com/Zero-S1/JD_tools/issues/15#issuecomment-671997226)

嗯嗯好的我试下py版本的

**Comment by lxk0301** [comment]
> > @mxzsw123456 阿里云 可以考虑用这个 https://github.com/Zero-S1/JD_tools ,
> > 作者有说 阿里云可以 [Zero-S1/JD_tools#15 (comment)](https://github.com/Zero-S1/JD_tools/issues/15#issuecomment-671997226)
> 
> 嗯嗯好的我试下py版本的

py版本的可以吗?

**Comment by mxzsw123456** [comment]
> > > @mxzsw123456 阿里云 可以考虑用这个 https://github.com/Zero-S1/JD_tools ,
> > > 作者有说 阿里云可以 [Zero-S1/JD_tools#15 (comment)](https://github.com/Zero-S1/JD_tools/issues/15#issuecomment-671997226)
> > 
> > 
> > 嗯嗯好的我试下py版本的
> 
> py版本的可以吗?
![error](https://user-images.githubusercontent.com/47170569/89996333-3edfb780-dcbd-11ea-98fe-350058825669.png)
可能是我操作问题一直报错

**Comment by lxk0301** [comment]
@mxzsw123456  那边作者说py版本的阿里云可以，   你这是阿里云吗？  如果是的话还不行， 建议跟那边讨教一下

**Comment by lxk0301** [comment]
@XiaYi1002 @mxzsw123456 
![image](https://user-images.githubusercontent.com/21308593/90583113-eef37a00-e201-11ea-973c-e6cb79d05732.png)

**Comment by XiaYi1002** [comment]
> @XiaYi1002 @mxzsw123456
> ![image](https://user-images.githubusercontent.com/21308593/90583113-eef37a00-e201-11ea-973c-e6cb79d05732.png)

py吗

**Comment by lxk0301** [comment]
@XiaYi1002 
不是。 我的脚本，node.js

**Comment by mxzsw123456** [comment]
> @XiaYi1002
> 不是。 我的脚本，node.js

对的，是楼主大佬的js脚本放在腾讯云函数测试报错

**Comment by lxk0301** [comment]
> > @XiaYi1002
> > 不是。 我的脚本，node.js
> 
> 对的，是楼主大佬的js脚本放在腾讯云函数测试报错

。。。。我是说。上面截图成功的。是我的脚本。报错事因为你们没找到使用方法

**Comment by 56warmers** [comment]
> 
> 
> > @XiaYi1002
> > 不是。 我的脚本，node.js
> 
> 对的，是之前把楼主大佬的 js 脚本放在腾讯云函数的时候测试报错，现在加上段代码正常了！

请问如何添加代码？
