### ISSUE TITLE
家庭号可以弄一下不？1000幸福值可以兑换30京豆

### ISSUE THREAD

**Issue by zero205** [lxk0301/scripts#103]
路径：京东app->我的->右上角家庭号

**Comment by zero205** [comment]
还有个活动，京东app->京东秒杀->天天秒红包。每天保底0.08

**Comment by zero205** [comment]
另外附上本人4个号的互助码，一起互助。

农场：35fcfda6d3af48e7afe79f5e18a39e55&5a41b6db624346cdbe347b61279fda8f&3fa4d41fe66e47bd8a9549e33e3b9b54&5dc8a7b9f4544a8ca79f8cf62d0c7623
萌宠：MTAxODc2NTEzMDAwMDAwMDAxMzgwNTcyNw==&MTAxODc2NTEzMzAwMDAwMDAxMzgwNDg3OQ==&MTE1NDAxNzcwMDAwMDAwMzUxNDMwMDc=
种豆：mlrdw3aw26j3xc6xycqtc74umufg2kphl3yfaxy&4npkonnsy7xi3ii7u6y52byc4urucexhl2wh2pq&olmijoxgmjutydymkyc56wollvia4yorekjt5ky&q7knrx5fitalyburqkflsm4jjq3h7wlwy7o5jii

**Comment by JustinChris-freshman** [comment]
谢谢分享

**Comment by JustinChris-freshman** [comment]
我的农场只有一个：24f3efb11ce04254a38b4d0bf0183493

**Comment by zero205** [comment]
> 我的农场只有一个：24f3efb11ce04254a38b4d0bf0183493

收到

**Comment by zero205** [comment]
> 我的农场只有一个：24f3efb11ce04254a38b4d0bf0183493
> 种豆：4npkonnsy7xi2dkkbvl643342m5of4rpapky3ha

**前面的助力码填错了，已全部更正**
