### ISSUE TITLE
能不能写个几种助力码的获取方法?

### ISSUE THREAD

**Issue by iwshw888** [lxk0301/scripts#115]
**东东农场互助码、东东萌宠互助码、种豆得豆互助码，这几个代码的获取能不能出个简单的说明?
比如抓包时链接关键词之类的,找了这么久就只找到了种豆得豆的助力码在哪,其它两个都没找到.谢谢!**

**Comment by landcruser** [comment]
到相应脚本去找，在每个actions里看执行结果就有，我说的是github跑

> **东东农场互助码、东东萌宠互助码、种豆得豆互助码，这几个代码的获取能不能出个简单的说明? 比如抓包时链接关键词之类的,找了这么久就只找到了种豆得豆的助力码在哪,其它两个都没找到.谢谢!**

**Comment by iwshw888** [comment]
> 运行脚本。看脚本的打印日志，既然你种豆的都找到了。其他的也是一样的呀

明白,感谢大佬提示
