### ISSUE TITLE
jd_unsubscribe默认情况下无法取消商品收藏

### ISSUE THREAD

**Issue by EchoChan314** [lxk0301/scripts#125]
之前在QX运行的时候也发现这个问题，但在boxjs里面改取消商品收藏的数量后就可以正常运行了。
然后这次在GitHub action运行，发现无法取消商品收藏，但可以取消店铺关注。

**Comment by lxk0301** [comment]
OK。有空我看看

**Comment by lxk0301** [comment]
已解决，是我有次本地调试，把取关商品的给关闭了，提交的时候忘记恢复了
