### ISSUE TITLE
Action未能在指定时间运行

### ISSUE THREAD

**Issue by huyinjie** [lxk0301/scripts#130]
比如应该在0点运行的Action，每次都在00:38:26左右运行，请问该怎么设置呢

**Comment by lxk0301** [comment]
@huyinjie action的时间是UTC-0时间。不是北京时间。要自定义设置cron在yml文件里面设置

**Comment by huyinjie** [comment]
@lxk0301 刚刚打错了数字，比如cron为 `0 0,8,16 * * *` ，Action每次运行时候都不在0点整点，一般过半小时才会自动运行

**Comment by lxk0301** [comment]
@huyinjie 你看不懂话吗？我说过了有延迟。 教程里面也写过。大概延迟15分钟左右

**Comment by huyinjie** [comment]
@lxk0301 懂了 感谢大佬

**Comment by lxk0301** [comment]
所以一般类的脚本可以在github运行。

但是对于抢购类的。对于时间很严格的。 还是建议用其他方式运行脚本。
