### ISSUE TITLE
基本完成docker环境定时运行脚本

### ISSUE THREAD

**Issue by EvineDeng** [lxk0301/scripts#134]
基本完成docker环境定时运行脚本，如果需要在nas上或vps上使用，可查看：https://github.com/EvineDeng/jd-base

适合人群：
- 每个月要超出 Github Action 免费使用时长的；
- 没有水果机的；
- 想要精确控制脚本运行时间的（Github Action无法精确运行）；
- 有nas或者vps等7×24运行设备的。

**Comment by EvineDeng** [comment]
@lxk0301 可以增加到readme中吗？

**Comment by lxk0301** [comment]
可以。你也可pr过来。放到方法三下面。
新建方法四即可。

**Comment by EvineDeng** [comment]
> 可以。你也可pr过来。放到方法三下面。
> 新建方法四即可。

好了，其实这还是我人生第一次写脚本，人生第一次发PR。

**Comment by jjss520** [comment]
docker的可以自动更新代码吗？

**Comment by EvineDeng** [comment]
> docker的可以自动更新代码吗？

两种docker方式都会自动更新。

**Comment by paopaojun** [comment]
没玩过 docker的哭了
