### ISSUE TITLE
JD_Joy_help 怎么使用？

### ISSUE THREAD

**Issue by hajiuhajiu** [lxk0301/scripts#136]
使用方法：
①设置好相应软件的重写
②从京东APP宠汪汪->领狗粮->邀请好友助力，分享给你小号微信或者微信的文件传输助手。 自己再打开刚才的分享，助力成功后，退出小程序重新进去刚才分享的小程序即可
③如提示好友人气旺，说明此好友已满了三人助力，需重新进出小程序，重新进入来客有礼-宠汪汪。

在workflow里没有，添加后需要作哪些改动，

**Comment by lxk0301** [comment]
这个是iOS手机上面用的。
