### ISSUE TITLE
新活动 超级王牌计划

### ISSUE THREAD

**Issue by leeyiding** [lxk0301/scripts#137]
活动时间10.19-11.11

https://lzdz-isv.isvjcloud.com/dingzhi/fashion/opencard/activity?activityId=ec1095976b174f04af042539e452be29&sid=2b55c5b18463ef2a423a5ff363a505dw&un_area=7_412_47301_0

**Comment by lxk0301** [comment]
这个有必要用脚本去做？好像没几个浏览任务吧
