### ISSUE TITLE
大兄弟,宠汪汪喂食接口逻辑是不是改了?

### ISSUE THREAD

**Issue by BuleB** [lxk0301/scripts#138]
我刚才看了一下,走的是没吃完的code,但是JD里面是没有食物的

**Comment by BuleB** [comment]
@lxk0301 手动@大兄弟

**Comment by lxk0301** [comment]
不知道哎， 我没动过脚本，除非是京东那边改了， 但是我这边目前正常，

你在运行一次脚本看看，然后看看APP里面宠汪汪是否在吃东西了?

**Comment by BuleB** [comment]
> 不知道哎， 我没动过脚本，除非是京东那边改了， 但是我这边目前正常，
> 
> 你在运行一次脚本看看，然后看看APP里面宠汪汪是否在吃东西了?

那我晓得了,应该是我这边的问题,我今天加了一个cookie,我去确认下

**Comment by BuleB** [comment]
我错了,cookie我给整错了
