### ISSUE TITLE
有交流群吗

### ISSUE THREAD

**Issue by javahokky** [lxk0301/scripts#139]
各位，有交流群吗？[https://t.me/JD_fruit_pet](url) 访问不了

**Comment by Ouyangchenxing** [comment]
宠汪汪又有浏览任务了，十个一百积分

**Comment by lxk0301** [comment]
> 各位，有交流群吗？[https://t.me/JD_fruit_pet](url) 访问不了

需要科学上网，还需下载APP（telegram）

**Comment by lxk0301** [comment]
> 宠汪汪又有浏览任务了，十个一百积分

已加上

**Comment by javahokky** [comment]
> > 各位，有交流群吗？[https://t.me/JD_fruit_pet](url) 访问不了
> 
> 需要科学上网，还需下载APP（telegram）

明白

**Comment by anddyyoo** [comment]
对的

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: javahokky <notifications@github.com>
发送时间: Tuesday, October 20, 2020 4:53:38 PM
收件人: lxk0301/scripts <scripts@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [lxk0301/scripts] 有交流群吗 (#139)


Closed #139<https://github.com/lxk0301/scripts/issues/139>.

―
