### ISSUE TITLE
京小超

### ISSUE THREAD

**Issue by bestfearless** [lxk0301/scripts#15]
大佬好，

1，京小超能不能做到自动上架限时产品呢？（有空余货架的情况下，限时产品确实很多蓝币，一天几万个）
2，能不能把兑换京豆并到京小超脚本呢？那个领取蓝币只有1000个，还比较费时间，有点鸡肋
3，能不能添加一个兑换1000京豆的机会呢，蓝币越来越多了，每天20个京豆，根本兑不完蓝币

感谢大佬的无私分享脚本，大佬辛苦了

**Comment by lxk0301** [comment]
第二点, 主要是领蓝币的脚本 ,只需一天运行一次即可,所以兑换京豆才放在这边 , 你可凌晨睡觉的时候运行.  
京小超考虑需隔几个小时运行一次,

**Comment by tiantianwahaha** [comment]
1. 我给京小超添加了自动在第一个货架上上架限时产品，并且每天升级一个最便宜的物品做任务的功能。请问怎么只Pull request给大佬你jd_superMarket.js这一个文件。
2. 我尝试添加自动完成商圈任务(抓包看就是和普通任务比换了一个参数smtg_doPKTask)，但是总提示the current API does not exist，请问大佬知道是怎么回事吗。

**Comment by lxk0301** [comment]
@tiantianwahaha  单文件pull request,我也不清楚, 你可以直接发在issues里面. 

第二个文件, 看提示是说这个api不存在

**Comment by Zero-S1** [comment]
> 1. 我给京小超添加了自动在第一个货架上上架限时产品，并且每天升级一个最便宜的物品做任务的功能。请问怎么只Pull request给大佬你jd_superMarket.js这一个文件。
> 2. 我尝试添加自动完成商圈任务(抓包看就是和普通任务比换了一个参数smtg_doPKTask)，但是总提示the current API does not exist，请问大佬知道是怎么回事吗。

看是不是 `smtg_doPkTask`  Pk的k小写

**Comment by MisterGlasses** [comment]
> 1. 我给京小超添加了自动在第一个货架上上架限时产品，并且每天升级一个最便宜的物品做任务的功能。请问怎么只Pull request给大佬你jd_superMarket.js这一个文件。
> 2. 我尝试添加自动完成商圈任务(抓包看就是和普通任务比换了一个参数smtg_doPKTask)，但是总提示the current API does not exist，请问大佬知道是怎么回事吗。

自动上架限时商品怎么没下文了？

**Comment by tiantianwahaha** [comment]
> > 1. 我给京小超添加了自动在第一个货架上上架限时产品，并且每天升级一个最便宜的物品做任务的功能。请问怎么只Pull request给大佬你jd_superMarket.js这一个文件。
> > 2. 我尝试添加自动完成商圈任务(抓包看就是和普通任务比换了一个参数smtg_doPKTask)，但是总提示the current API does not exist，请问大佬知道是怎么回事吗。
> 
> 自动上架限时商品怎么没下文了？

去我github页面直接用jd_superMarket.js替换你的就行了

**Comment by MisterGlasses** [comment]
> jd_superMarket.js

为啥不pull 一下？

**Comment by MisterGlasses** [comment]
这个可以close了

**Comment by lxk0301** [comment]
已添加
