### ISSUE TITLE
京东种豆得豆, 失败! 啥问题

### ISSUE THREAD

**Issue by hajiuhajiu** [lxk0301/scripts#154]
❌ 京东种豆得豆, 失败! 原因: TypeError: Cannot read property 'jwordShareInfo' of undefined!

**Comment by lxk0301** [comment]
再跑一次。

**Comment by hajiuhajiu** [comment]
手动跑了几次还不行，sharecode也改了，也不行

**Comment by lxk0301** [comment]
这个问题检查自身网络环境
