### ISSUE TITLE
jd_unsubscribe.js的参数不要用换行符分隔

### ISSUE THREAD

**Issue by smilingpoplar** [lxk0301/scripts#158]
群晖配置的环境变量里输入`\n`无效，输入`\\n`转义又不被脚本识别

**Comment by smilingpoplar** [comment]
使用`\n`脚本可以识别。我原先是自定义my_crontab_list.sh未生效。

**Comment by lxk0301** [comment]
> 使用`\n`脚本可以识别。我原先是自定义my_crontab_list.sh未生效。

你能解决就行。我脚本就不做兼容了
