### ISSUE TITLE
星推官是个啥，能分享一下活动入口吗

### ISSUE THREAD

**Issue by fm1223** [lxk0301/scripts#163]
说话lxk0301能收我为徒么🤣

**Comment by lxk0301** [comment]
活动地址的话，脚本里面有写

收徒就算了，没时间。

**Comment by fm1223** [comment]
> 活动地址的话，脚本里面有写
> 
> 收徒就算了，没时间。

**Comment by fm1223** [comment]
> 活动地址的话，脚本里面有写
> 
> 收徒就算了，没时间。

哈哈，我也想写一个，抓的包全是ssl乱码，看的头皮发麻。能在一堆接口里找到为数不多有用的，还是厉害。
