### ISSUE TITLE
希望增加宠旺旺页面每日签到的支持

### ISSUE THREAD

**Issue by chenyz1984** [lxk0301/scripts#165]
![image](https://user-images.githubusercontent.com/20869868/96824633-d69e1680-1461-11eb-89da-0543e00c0f61.png)

**Comment by lxk0301** [comment]
我APP里面没有这个哎， 你怎么弄出来的？点领狗粮吗？

**Comment by tommyhe1217** [comment]
app里面不出来的，点击签到会直接跳转小程序的

**Comment by lxk0301** [comment]
那我懂了 ，这个做不了。因为要跳转到小程序那边，需要用到那边的token，此token失效很短。2个多小时就过期

**Comment by chenyz1984** [comment]
> 我APP里面没有这个哎，
> 
> 1、你怎么弄出来的？点`领狗粮`吗？
> 宠汪汪页面顶端直接就显示的。
> 2、还有就是点签到，是不是会跳转到微信小程序里面去？
点击签到，会跳转到微信小程序“来客有礼”，并在该小程序中签到。
