### ISSUE TITLE
我想问下两个docker运行方式，会同步更新最新脚本么

### ISSUE THREAD

**Issue by skypjsfly** [lxk0301/scripts#168]
看了下教程，两个docker方式，第二种好像是第一次运行的时候把JS下载到本地执行，这样的话，这种方法应该不会自动更新js脚本吧？然后第一种方法没看到有下载js到本地，不知道原理是啥

**Comment by EvineDeng** [comment]
方法一脚本在构建镜像时已经存在了，然后通过定时任务更新，方法二在创建容器时通过entrypoint自动摘拉取代码，通过定时任务更新。

**Comment by iouAkira** [comment]
> 看了下教程，两个docker方式，第二种好像是第一次运行的时候把JS下载到本地执行，这样的话，这种方法应该不会自动更新js脚本吧？然后第一种方法没看到有下载js到本地，不知道原理是啥

留意下 `crontab_list.sh` 里面的定时任务

**Comment by skypjsfly** [comment]
现在遇到新问题，已经新建了docker的镜像，运行后就三条日志
crond[7]: crond (busybox 1.31.1) started, log level 8
Welcome to Node.js v12.18.4.
Type ".help" for more information.
这是咋回事

**Comment by iouAkira** [comment]
@skypjsfly 运行日志在 logs 目录下面，每个任务有对应的log文件，需要看的，就挂载一下

**Comment by skypjsfly** [comment]
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/scripts/jd_joy_feedPets.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
这是没下载js文件？

**Comment by iouAkira** [comment]
你用的哪个镜像？这是 `log` 文件里面报错？ 你的运行环境是啥 ？`docker log` 也发一下才能看问题？

**Comment by skypjsfly** [comment]
就是logs文件夹里面jd_joy_feedPets.log的日志，用的docker方式一那个镜像（akyakya），在群晖docker里面运行的，因为镜像删除过，docker log 里面日志清空了。。

现在logs文件夹里面多了个pull.log，显示
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by skypjsfly** [comment]
docker日志
crond[7]: USER root pid  19 cmd node /scripts/jd_joy_feedPets.js >> /scripts/logs/jd_joy_feedPets.log 2>&1
crond[7]: USER root pid  26 cmd crontab /scripts/docker/${CRONTAB_LIST_FILE}

**Comment by iouAkira** [comment]
@skypjsfly #是否使用了自定义定时任务,这个名字改成my_crontab_list.sh
    - CRONTAB_LIST_FILE=crontab_list.sh
少了这个环境变量

**Comment by skypjsfly** [comment]
没有自定义定时任务，这个环境变量是有的

**Comment by iouAkira** [comment]
> 就是logs文件夹里面jd_joy_feedPets.log的日志，用的docker方式一那个镜像（akyakya），在群晖docker里面运行的，因为镜像删除过，docker log 里面日志清空了。。
> 
> 现在logs文件夹里面多了个pull.log，显示
> fatal: not a git repository (or any parent up to mount point /)
> Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

你是导入的，还是自己手动建的容器，如果导入的话，敏感信息删掉，发一下导入的 `json`，手动建的需要看一下你配置过程中环境变量都配置了哪些。或者你直接把你的容器导出一份 `json` 发上来看一下

**Comment by skypjsfly** [comment]
我是想把所有的js文件都映射出来，不知道是不是这个的原因

**Comment by skypjsfly** [comment]
还有一个问题，就是json的那个文件夹里面没有serve酱的密钥填写的地方

**Comment by smilingpoplar** [comment]
@skypjsfly 照着https://github.com/lxk0301/scripts/blob/master/githubAction.md添加环境变量到json就行

**Comment by iouAkira** [comment]
> 我是想把所有的js文件都映射出来，不知道是不是这个的原因

😂，如果想这样的话，你的群晖上的 `scripts` 要有一套完整的脚本，如果你的  `scripts`  是一个空文件夹的话，挂载就会把里面已有的覆盖掉。
想同步里面的脚本 你可以挂一个 别的名字空文件夹( `xxxx` ) 到 容器里面 `/xxxx`，然后自定`crontab`加一下定时复制一份到  `/xxxx`；
如果是想修改某个 `js` 文件的话建议指定单个文件名挂载 例如 `xxxx.js:/scripts/xxxx.js`

**Comment by lxk0301** [comment]
> @skypjsfly 照着https://github.com/lxk0301/scripts/blob/master/githubAction.md 的Secrets全集合添加环境变量到json就行

不过好像JD_COOKIE的环境变量不能按Secrets全集合来添加吧？你今天早上不是新增了一个嘛

**Comment by smilingpoplar** [comment]
@lxk0301 用JD_COOKIE，json里再配环境变量CDN_JD_DAILYBONUS为true，两个一起。

**Comment by skypjsfly** [comment]
好像可以了，还有个问题，就是docker默认与北京时间有8小时时差，这个没有影响吗

**Comment by skypjsfly** [comment]
好吧。。。我在测试下，目前没啥问题了，谢谢大神

**Comment by lxk0301** [comment]
> docker默认与北京时间有8小时时差

docker默认与北京时间有8小时时差????

也是UTC-0？


我记得上面两位说过好像是北京时间呀

**Comment by skypjsfly** [comment]
突然想到还有一个老生常谈的问题，docker这种方式任务的执行时间应该是基于docker所在的环境的时间，如果环境与标准北京时间存在几秒的偏差，可能会导致签到失败，是否要将整个任务往后推迟3-5秒，避免一些凌晨签到失败。

**Comment by smilingpoplar** [comment]
@skypjsfly 有点道理，那把0时0分的命令sleep 5;

**Comment by skypjsfly** [comment]
> @skypjsfly 有点道理，那把0时0分的命令sleep 5;

我不会啊，我只会提需求，技能水平为0

**Comment by iouAkira** [comment]
不会的，这种偏差的概率太低了
![image](https://user-images.githubusercontent.com/6993269/96862298-dcaeea00-1497-11eb-896c-540275698af1.png)

**Comment by smilingpoplar** [comment]
要用自定义的my_crontab_list.sh，改成这样：
```
0 */1 * * * sleep 5; git -C /scripts/ pull >> /scripts/logs/pull.log 2>&1
2 */1 * * * sleep 5; crontab /scripts/docker/${CRONTAB_LIST_FILE}
0 0-18/6 * * * sleep 5; node /scripts/jd_818.js >> /scripts/logs/jd_818.log 2>&1
0 0,12,18 * * * sleep 5; node /scripts/jd_bean_sign.js >> /scripts/logs/jd_bean_sign.log 2>&1
...
```
小众需求

**Comment by skypjsfly** [comment]
@smilingpoplar 懂了，谢谢大佬

**Comment by iouAkira** [comment]
用了自定义的，如果有新的任务自己记得往里面加，还有这个 `CRONTAB_LIST_FILE ` 这个环境变量值要改成自己的文件名，另外任务定义不会跟上游库里面更新的走了。

**Comment by skypjsfly** [comment]
> 用了自定义的，如果有新的任务自己记得往里面加，还有这个 `CRONTAB_LIST_FILE ` 这个环境变量值要改成自己的文件名，另外任务定义不会跟上游库里面更新的走了。

如果用默认的crontab_list，就会自动更新新增的任务对吧？

**Comment by iouAkira** [comment]
嗯，就是有加新的任务的时候需要 @lxk0301 或者有人pr 在crontab_list.sh里面维护一下

**Comment by skypjsfly** [comment]
懂了，谢谢大佬
