### ISSUE TITLE
docker上静默运行的设置可用吗？

### ISSUE THREAD

**Issue by smilingpoplar** [lxk0301/scripts#175]
@iouAkira 我在群晖的json中设置了静默运行的环境参数，但还是会收到京小超、旺旺积分兑换奖品、京豆签到的通知。
你试过静默运行设置吗？

```
     {
         "key" : "FRUIT_NOTIFY_CONTROL",
         "value" : "true"
      },
      {
         "key" : "PET_NOTIFY_CONTROL",
         "value" : "true"
      },
      {
         "key" : "JD_JOY_REWARD_NOTIFY",
         "value" : "true"
      },
      {
         "key" : "MARKET_REWARD_NOTIFY",
         "value" : "true"
      },
```

**Comment by iouAkira** [comment]
> @iouAkira 我在群晖的json中设置了静默运行的环境参数，但还是会收到京小超、旺旺积分兑换奖品、京豆签到的通知。
> 你试过静默运行设置吗？
> 
> ```
>      {
>          "key" : "FRUIT_NOTIFY_CONTROL",
>          "value" : "true"
>       },
>       {
>          "key" : "PET_NOTIFY_CONTROL",
>          "value" : "true"
>       },
>       {
>          "key" : "JD_JOY_REWARD_NOTIFY",
>          "value" : "true"
>       },
>       {
>          "key" : "MARKET_REWARD_NOTIFY",
>          "value" : "true"
>       },
> ```

`docker exec -it jd_sctipts /bin/sh` 进容器 `env` 看看环境变量有没有生效。

**Comment by smilingpoplar** [comment]
@iouAkira 进容器echo了下，生效了

**Comment by iouAkira** [comment]
> @iouAkira 进容器echo了下，生效了

那你在容器里面 ，手动执行  `node jd_fruit.js` 看看，`env` 一下你的所有环境变量截图看看

**Comment by smilingpoplar** [comment]
```
/scripts # env
CDN_JD_DAILYBONUS=true
FRUIT_BEAN_CARD=true
BUSINESS_CIRCLE_JUMP=true
HOSTNAME=jd_scripts
SHLVL=1
HOME=/root
SUPERMARKET_SHARECODES=95OHuGQqs0SmJORw
CRONTAB_LIST_FILE=my_crontab_list.sh
JD_JOY_REWARD_NOTIFY=true
PUSH_KEY=SCU231T6be388f9ca4951a28dfc8b11dcdde8c09
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PLANT_BEAN_SHARECODES=77gnpkk5f3yuqkcgccpjq72g3e
MARKET_COIN_TO_BEANS=20
FruitShareCodes=9367d86b271e4a47afd8e4ac8c008f42
JOY_FEED_COUNT=80
SUPERMARKET_UPGRADE=true
PETSHARECODES=MTAxODc2NTE0NzAwMDAwMDAyOTM0MjMxNQ==
JD_COOKIE=pt_key=AAJfkQ_bADCYoMiIt6h1ioy3mfkNqYj_hUwr2XiLOB0OdmXUYAg9vZSsf-d7emdL9ZJsis;pt_pin=smilingpoplarr;
PET_NOTIFY_CONTROL=true
FRUIT_NOTIFY_CONTROL=true
MARKET_REWARD_NOTIFY=true
PWD=/scripts
UN_SUBSCRIBES=100
100
```

**Comment by iouAkira** [comment]
我测试了一下没有问题
![image](https://user-images.githubusercontent.com/6993269/96887535-41c60800-14b7-11eb-8a5c-3cd03e065c6f.png)

**Comment by smilingpoplar** [comment]
奇怪了，我换个通知服务看看

**Comment by lxk0301** [comment]
隐私信息去掉 @smilingpoplar

**Comment by smilingpoplar** [comment]
@lxk0301 去掉了，没隐私

**Comment by lxk0301** [comment]
你刚才京东cookie和通知参数有添加上去了

**Comment by smilingpoplar** [comment]
随机删字符了

**Comment by smilingpoplar** [comment]
@iouAkira 我刚犯糊涂了，jd_fruit.js脚本没问题，是我说的那3个脚本：京小超兑换奖品成功`jd_blueCoin.js`、宠旺旺积分兑换奖品成功`jd_joy_reward.js`、京豆签到`jd_bean_sign.js`。

**Comment by lxk0301** [comment]
@smilingpoplar jd_bean_sign.js目前不支持关闭通知

**Comment by smilingpoplar** [comment]
@lxk0301 对，刚修改，你回得快。

**Comment by lxk0301** [comment]
我不知道是不是你们那边设置的问题。虽然宠汪汪兑换奖品关闭通知的secret是JD_JOY_REWARD_NOTIFY，但是我脚本里面拿的是process.env.jdJoyRewardNotify。

@iouAkira @smilingpoplar 

![49C52087-894C-4E23-B10C-073E56C9E88F](https://user-images.githubusercontent.com/21308593/96890875-acc50e00-14ba-11eb-9861-a69f1422e042.jpeg)

**Comment by iouAkira** [comment]
嗯，是要按照脚本里面的取值来，应该配置  `jdJoyRewardNotify`

**Comment by smilingpoplar** [comment]
action workflow里有个转换，docker里没有

![截屏2020-10-22 下午11 05 40](https://user-images.githubusercontent.com/219728/96891473-4987ab80-14bb-11eb-9660-25bbf21481fc.png)

**Comment by smilingpoplar** [comment]
@lxk0301 这个最终还是脚本作者改更好吧，变量名变统一。

**Comment by lxk0301** [comment]
> @lxk0301 这个最终还是脚本作者改更好吧，变量名变统一。

好。之前只想到action的情况。没想到你们docker运行环境也是拿process.env的
