### ISSUE TITLE
脚本内外的环境变量名不一致，docker中忘记额外的转换出bug

### ISSUE THREAD

**Issue by smilingpoplar** [lxk0301/scripts#177]
jdJoyRewardNotify和JD_JOY_REWARD_NOTIFY，jdSuperMarketRewardNotify和MARKET_REWARD_NOTIFY

btw, **_NOTIFY=true表示不发通知，反直觉，变量名起反了

**Comment by smilingpoplar** [comment]
btw, **_NOTIFY=true表示不发通知，完全反直觉，变量名起反了

**Comment by smilingpoplar** [comment]
还有PetShareCodes和PETSHARECODES名称不同，导致docker设置萌宠互助不生效

**Comment by lxk0301** [comment]
> jdJoyRewardNotify和JD_JOY_REWARD_NOTIFY，jdSuperMarketRewardNotify和MARKET_REWARD_NOTIFY
> 
> btw, **_NOTIFY=true表示不发通知，反直觉，变量名起反了

你说的`**_NOTIFY`是指这个 `jdNotify`?

**Comment by smilingpoplar** [comment]
> > jdJoyRewardNotify和JD_JOY_REWARD_NOTIFY，jdSuperMarketRewardNotify和MARKET_REWARD_NOTIFY
> > btw, **_NOTIFY=true表示不发通知，反直觉，变量名起反了
> 
> 你说的`**_NOTIFY`是指这个 `jdNotify`?

我指所有的xxx_NOTIFY环境变量，应该xxx_NOTIFY=true表示发通知，=false表示静默通知，意思才对吧。

**Comment by lxk0301** [comment]
> > > jdJoyRewardNotify和JD_JOY_REWARD_NOTIFY，jdSuperMarketRewardNotify和MARKET_REWARD_NOTIFY
> > > btw, **_NOTIFY=true表示不发通知，反直觉，变量名起反了
> > 
> > 
> > 你说的`**_NOTIFY`是指这个 `jdNotify`?
> 
> 我指所有的xxx_NOTIFY环境变量，应该xxx_NOTIFY=true表示发通知，=false表示静默通知，意思才对吧。

其实他的本意是指静默运行(静默运行的意思是不发通知)，  true表示静默运行

**Comment by smilingpoplar** [comment]
那应该叫xxx_NOTIFY_SILIENT，README里面每次这种环境变量出现后面都得带解释，就是变量名取错了

**Comment by lxk0301** [comment]
> 那应该叫xxx_NOTIFY_SILENT，README里面每次这种环境变量出现后面都得带解释，就是变量名取错了

嗯， 当初确实是名字取错了 ，不过我脚本里面都有汉字解释，但是`xxx_NOTIFY`不影响你们那边，你们docker那边控制是否通知，有别的单独环境变量的。


还有就是现在环境变量不一致的情况已经更新， 你有空可帮忙检查一下，看看是否有误。

**Comment by smilingpoplar** [comment]
@lxk0301 
![截屏2020-10-24 上午11 08 13](https://user-images.githubusercontent.com/219728/97066624-66ba9800-15e9-11eb-8bf0-2ef3abe9560a.png)
