### ISSUE TITLE
github action方式 是不是获取cookie的方法有问题

### ISSUE THREAD

**Issue by han8435762** [lxk0301/scripts#184]
很好用 github还有workflow 不错 不过不知道 是不是获取cookie的方法有问题
我直接按照教程 copy(document.cookie) 获取cookie填入JD_COOKIE 运行时总是提示 cookie失效
然后直接从网络请求中把请求头中的cookie填入JD_COOKIE 就能成功运行

比较了一下 差了一个 TrackerID 怀疑是它造成的

**Comment by lxk0301** [comment]
这么大的黑体你都看不到。有啥办法？？

![D6626A05-D302-4374-AE38-896B41726D18](https://user-images.githubusercontent.com/21308593/96989101-cbc5ad80-1557-11eb-8d22-baa6f9772adb.jpeg)
