### ISSUE TITLE
群晖用户使用方法一无法建立容器

### ISSUE THREAD

**Issue by wenjiefu-cn** [lxk0301/scripts#185]
群晖用户在docker中导入.json文件提示“映像akyakya/jd_scripts不存在”

**Comment by lxk0301** [comment]
@wenjiefu-cn @@EvineDeng

**Comment by iouAkira** [comment]
@wenjiefu-cn 你镜像都没拉下来啊

**Comment by wenjiefu-cn** [comment]
> @wenjiefu-cn 你镜像都没拉下来啊

大佬，我docker目录下的教程走的，没看见哪里拉了镜像啊，是我才菜了。
能不能麻烦说一下镜像哪里拉？
sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
这两行命令我是运行了的

**Comment by iouAkira** [comment]
@wenjiefu-cn docker注册表搜 akyakya/jd_scripts 然后双击就拉下来了

**Comment by wenjiefu-cn** [comment]
> @wenjiefu-cn docker注册表搜 akyakya/jd_scripts 然后双击就拉下来了

啊啊，可以了，谢谢啊。对了提个建议，直接搜akyakya/jd_scripts搜不到，搜jd_scripts就有了。
最后感谢大佬回复，谢谢。
