### ISSUE TITLE
我想在GITHUB上只运行部分脚本，如何设置

### ISSUE THREAD

**Issue by leecheng310** [lxk0301/scripts#197]

**Comment by lxk0301** [comment]
@leecheng310 去看教程。里面有提供如何禁用单个脚本（action）

**Comment by leecheng310** [comment]
教程里那个图片打不开··

**Comment by lxk0301** [comment]
你不能科学上网？？


https://gitee.com/lxk0301/scripts/blob/master/icon/disable-action.jpg

**Comment by leecheng310** [comment]
丢人了··最近搞京东签到才接触这些，小白一个，之前没搞过科学上网，需求不大，看来要研究研究了

顺便问下，GITHUB每月免费运行时长在哪能查到已用时长的

**Comment by leecheng310** [comment]
再问问
这么设置后上游有更新是否正常会接受更新，但是项目保持不运行状态

**Comment by lxk0301** [comment]
@leecheng310 开源仓库免费运行时长不限制

**Comment by lxk0301** [comment]
@leecheng310 教程下面有写同步更新上游的三种方式，你自己去选择一种

**Comment by leecheng310** [comment]
方案A - 强制远程分支覆盖自己的分支(新手推荐使用)

**Comment by lxk0301** [comment]
不会

**Comment by leecheng310** [comment]
好的 谢谢
