### ISSUE TITLE
本地node运行js报错：this.got(...).on is not a function

### ISSUE THREAD

**Issue by muzi13** [lxk0301/scripts#198]
![image](https://user-images.githubusercontent.com/44488800/97079205-989d2000-1624-11eb-96f6-a23d9c223766.png)
这种错误怎么解决？

**Comment by lxk0301** [comment]
@muzi13 没安装依赖包。npm install一次

**Comment by muzi13** [comment]
> @muzi13 没安装依赖包。npm install一次
![image](https://user-images.githubusercontent.com/44488800/97081131-f0428800-1632-11eb-8222-d5f836cdacbc.png)
重新npm install了，还是出错

**Comment by lxk0301** [comment]
@muzi13 node版本用10x试试

**Comment by muzi13** [comment]
> @muzi13 node版本用10x试试
![image](https://user-images.githubusercontent.com/44488800/97084398-4ae6de80-1649-11eb-8d27-9445056f7f01.png)
还是不行，没有提示说是依赖包的问题吧

**Comment by muzi13** [comment]
又装了10.16版本的node

**Comment by lxk0301** [comment]
你自己的问题, 依赖包的位置,不在脚本根目录.................

**Comment by EvineDeng** [comment]
你先把当前目录使用cd命令切换到脚本目录，再运行npm install

**Comment by muzi13** [comment]
感谢 @lxk0301 @EvineDeng 的回答，按照EvineDeng的提示，脚本运行成功。
![image](https://user-images.githubusercontent.com/44488800/97103636-ab792880-16e8-11eb-8abf-da6327a9ddf3.png)

**Comment by muzi13** [comment]
已解决
