### ISSUE TITLE
求指导有个号签到等任务不完成？

### ISSUE THREAD

**Issue by jackelvon** [lxk0301/scripts#199]
大神，请帮我解决下问题：我两个cookies，为何用action运行完，一个号ok的，另一个号只做了京推官任务，其他的签到那些都没完成。
谢谢！盼赐教！

**Comment by jackelvon** [comment]
在线等

**Comment by lxk0301** [comment]
找自己原因 看了你的日志。你只给了一个账号的cookie

**Comment by jackelvon** [comment]
> 找自己原因 看了你的日志。你只给了一个账号的cookie

恩恩，后来我也看了下，有一个号的cookie失效了，现在好了，多谢！！！
