### ISSUE TITLE
jd818和xtg在nodejs能运行吗？

### ISSUE THREAD

**Issue by changer2222** [lxk0301/scripts#201]
一运行就是这样, 818也是这样，不知道哪儿修改

一共1个星推官任务，耗时会很久，请提前知晓

❌ 星推官, 失败! 原因: TypeError: this.got(...).on is not a function!

🔔星推官, 结束! 🕛 0.203 秒

**Comment by lxk0301** [comment]
@changer2222 下面的问题跟你一样

**Comment by lxk0301** [comment]
https://github.com/lxk0301/scripts/issues/198

**Comment by changer2222** [comment]
嗯，发完后我看到了，谢谢了，先close
