### ISSUE TITLE
京东增加了一个双十一活动，京东11.11大赢家，类似淘宝的养猫

### ISSUE THREAD

**Issue by hclasmn** [lxk0301/scripts#204]
京东增加了一个双十一活动，京东11.11大赢家，类似淘宝的养猫
26.0复制整段话 https://JJk8DnnIQAoBk0【全民在线营业啦，帮我助力，11.11一起来分京东10亿】復Ζнi这段話后~达开#BAImuEvvZb%→（京イ東）

**Comment by lxk0301** [comment]
目前不打算弄
