### ISSUE TITLE
两个号，求互助，手上萌宠还有四个位，农场三个位，种豆得豆两个位

### ISSUE THREAD

**Issue by Jelide** [lxk0301/scripts#211]
两个号，求互助，手上萌宠还有四个位，农场三个位，种豆得豆两个位
东东农场：ea9537d640c549028d3fb471ea109171

b215bc21f07b4b43825fa5b145fe3eed

东东萌宠：
MTE1NDQ5MzYwMDAwMDAwMzUyNjY5Njk

MTE1NDAxNzYwMDAwMDAwMzgyMDIxNDU

种豆得豆：
olmijoxgmjutyu3p2rpkpsfjvzt3epxju6tkclq

itplnhngh2a7f7apqfnhutkohg7jcgbpdxwvrrq

_Originally posted by @Timesflies in https://github.com/lxk0301/scripts/issues/66#issuecomment-716340034_

**Comment by HenryTSZ** [comment]
农场:
1e3a97f4ea004c8db1f285f126a5472a

萌宠:
MTE1NDAxNzgwMDAwMDAwMzgzMjEzMTE=

种豆得豆:
mlrdw3aw26j3x5amha4fu5pmlcnnqpnc7yywsda

**Comment by wheatwee** [comment]
> 两个号，求互助，手上萌宠还有四个位，农场三个位，种豆得豆两个位
> 东东农场：ea9537d640c549028d3fb471ea109171
> 
> b215bc21f07b4b43825fa5b145fe3eed
> 
> 东东萌宠：
> MTE1NDQ5MzYwMDAwMDAwMzUyNjY5Njk
> 
> MTE1NDAxNzYwMDAwMDAwMzgyMDIxNDU
> 
> 种豆得豆：
> olmijoxgmjutyu3p2rpkpsfjvzt3epxju6tkclq
> 
> itplnhngh2a7f7apqfnhutkohg7jcgbpdxwvrrq
> 
> _Originally posted by @Timesflies in [#66 (comment)](https://github.com/lxk0301/scripts/issues/66#issuecomment-716340034)_

已添加你2个账号
我的
种豆得豆 | btgrwkzaimj5uthjltldfpmsba
东东农场 | ee3ef1e9626b47978b67b2c8c25d44b2
东东萌宠 | MTEzMzI0OTE0NTAwMDAwMDAzNDg1NzQzMw==

**Comment by Timesflies** [comment]
> > 两个号，求互助，手上萌宠还有四个位，农场三个位，种豆得豆两个位
> > 东东农场：ea9537d640c549028d3fb471ea109171
> > b215bc21f07b4b43825fa5b145fe3eed
> > 东东萌宠：
> > MTE1NDQ5MzYwMDAwMDAwMzUyNjY5Njk
> > MTE1NDAxNzYwMDAwMDAwMzgyMDIxNDU
> > 种豆得豆：
> > olmijoxgmjutyu3p2rpkpsfjvzt3epxju6tkclq
> > itplnhngh2a7f7apqfnhutkohg7jcgbpdxwvrrq
> > _Originally posted by @Timesflies in [#66 (comment)](https://github.com/lxk0301/scripts/issues/66#issuecomment-716340034)_
> 
> 已添加你2个账号
> 我的
> 种豆得豆 | btgrwkzaimj5uthjltldfpmsba
> 东东农场 | ee3ef1e9626b47978b67b2c8c25d44b2
> 东东萌宠 | MTEzMzI0OTE0NTAwMDAwMDAzNDg1NzQzMw==

收到，已互助 @wheatwee

**Comment by Timesflies** [comment]
> 两个号，求互助，手上萌宠还有四个位，农场三个位，种豆得豆两个位
> 东东农场：ea9537d640c549028d3fb471ea109171
> 
> b215bc21f07b4b43825fa5b145fe3eed
> 
> 东东萌宠：
> MTE1NDQ5MzYwMDAwMDAwMzUyNjY5Njk
> 
> MTE1NDAxNzYwMDAwMDAwMzgyMDIxNDU
> 
> 种豆得豆：
> olmijoxgmjutyu3p2rpkpsfjvzt3epxju6tkclq
> 
> itplnhngh2a7f7apqfnhutkohg7jcgbpdxwvrrq
> 
> _Originally posted by @Timesflies in [#66 (comment)](https://github.com/lxk0301/scripts/issues/66#issuecomment-716340034)_

@Jelide 你是帮我助力了吗

**Comment by Jelide** [comment]
Timesflies <notifications@github.com>于2020年10月26日 周一下午6:20写道：

> 两个号，求互助，手上萌宠还有四个位，农场三个位，种豆得豆两个位
> 东东农场：ea9537d640c549028d3fb471ea109171
>
> b215bc21f07b4b43825fa5b145fe3eed
>
> 东东萌宠：
> MTE1NDQ5MzYwMDAwMDAwMzUyNjY5Njk
>
> MTE1NDAxNzYwMDAwMDAwMzgyMDIxNDU
>
> 种豆得豆：
> olmijoxgmjutyu3p2rpkpsfjvzt3epxju6tkclq
>
> itplnhngh2a7f7apqfnhutkohg7jcgbpdxwvrrq
>
> *Originally posted by @Timesflies <https://github.com/Timesflies> in #66
> (comment)
> <https://github.com/lxk0301/scripts/issues/66#issuecomment-716340034>*
>
> @Jelide <https://github.com/Jelide> 你是帮我助力了吗
>
是的。

**Comment by lxk0301** [comment]
互助去这里 https://github.com/lxk0301/scripts/issues/66  ,不新开已issues
