### ISSUE TITLE
可以增加一个版本日志么？

### ISSUE THREAD

**Issue by blacklisten** [lxk0301/scripts#227]
要定期同步主仓库的代码过去，但又不知道什么时间更新了什么，看commit还是有些乱

**Comment by lxk0301** [comment]
😂😂😂有点难。感觉没啥版本日志。都是随时更新的

**Comment by blacklisten** [comment]
> 😂😂😂有点难。感觉没啥版本日志。都是随时更新的

要不考虑一下引入cz？直接生成日志就可以了。https://www.blacklisten.cn/Git/commitizen%E8%A7%84%E8%8C%83commit/
