### ISSUE TITLE
MARKET_COIN_TO_BEANS京小超兑换京豆数量Name是否设置错误？

### ISSUE THREAD

**Issue by tommyhe1217** [lxk0301/scripts#235]
依据Name为作者提供的[MARKET_COIN_TO_BEANS]运行时提示：图一您输入的MARKET_COIN_T0_BEANS为非法数字，请重新填写。经过比对发现日志中的Name为[MARKET_COIN_T0（T零）_BEANS]，而变为（T零）是日志又提示
而将图二
Value值输入的是：柠檬果香洗手液，麻烦大佬帮忙看看，谢谢。
图一
![image](https://user-images.githubusercontent.com/66045818/97376575-adb1d180-18f8-11eb-89c7-653344c5fef3.png)
图2
![image](https://user-images.githubusercontent.com/66045818/97376602-bd311a80-18f8-11eb-887b-ff196dc39bd1.png)

**Comment by lxk0301** [comment]
MARKET_COIN_TO_BEANS 你输入的是什么？

脚本默认是不兑换的。

**Comment by tommyhe1217** [comment]
我输入的是   柠檬果香洗手液   需要加什么符号吗？
Name到底是输入那个，MARKET_COIN_TO_BEANS这个输入还是提示值不对

lxk0301 <notifications@github.com>于2020年10月29日 周四21:49写道：

**Comment by tommyhe1217** [comment]
> 好像没做云端兑换非京豆的兼容
> 
> 脚本默认是不兑换的。

教程说明栏位写到：
MARKET_COIN_TO_BEANS | 京小超兑换京豆数量 | 非必须 | 控制jd_blueCoin.js兑换京豆数量,可输入值为20或者1000的数字或者其他商品的名称,例如碧浪洗衣凝珠
-- | -- | -- | --

**Comment by lxk0301** [comment]
已修复,你重新测测看

**Comment by tommyhe1217** [comment]
> 已修复,你重新测测看
Name输入如下：
MARKET_COIN_TO_BEANS
Value值输入如下：
柠檬果香洗手液
运行后出现如下提示
![image](https://user-images.githubusercontent.com/66045818/97652070-8bef5080-1a98-11eb-9f70-c5acf5698b99.png)

![image](https://user-images.githubusercontent.com/66045818/97652093-96114f00-1a98-11eb-8608-9c67df399798.png)

再麻烦帮忙看看是哪里错误了。

**Comment by lxk0301** [comment]
> > 已修复,你重新测测看
> > Name输入如下：
> > MARKET_COIN_TO_BEANS
> > Value值输入如下：
> > 柠檬果香洗手液
> > 运行后出现如下提示
> > ![image](https://user-images.githubusercontent.com/66045818/97652070-8bef5080-1a98-11eb-9f70-c5acf5698b99.png)
> 
> ![image](https://user-images.githubusercontent.com/66045818/97652093-96114f00-1a98-11eb-8608-9c67df399798.png)
> 
> 再麻烦帮忙看看是哪里错误了。

你要更新我上游的仓库脚本

**Comment by tommyhe1217** [comment]
> 你要更新我上游的仓库脚本

謝謝，同步最新后已正常了。
