### ISSUE TITLE
腾讯云函数运行异常

### ISSUE THREAD

**Issue by leecheng310** [lxk0301/scripts#237]
代码上传保存后可以正常运行一次，第二次就一开始就结束了，没有执行任何代码
需要重新保存一次函数(不用改任何代码)，下一次又能正常执行
是啥原因

**Comment by lxk0301** [comment]
不知道。自己折腾琢磨吧

**Comment by leecheng310** [comment]
把要运行的JS全部代码复制到index的exports.main_handler = async (event, context, callback) => { 
之后，就正常，用require调用就只能正常运行一次
