### ISSUE TITLE
是否可以引入随机数，免得签到时间都太集中，被黑号

### ISSUE THREAD

**Issue by ppamoy** [lxk0301/scripts#238]
是否可以引入随机数，免得签到时间都太集中，被黑号

**Comment by lxk0301** [comment]
没办法做到。除非你自己去改cron

**Comment by ppamoy** [comment]
cron语句不支持随机数，是否可以在workflow脚本里引入随机数。如果是我们个人改，等您这边的脚本有更新，我们fork后又覆盖了。没事，就蛮讨论，感谢大佬。

**Comment by tanst** [comment]
可以用 shell 脚本，定时运行一个 shell 脚本，随机生成下次的 cron 计划任务
