### ISSUE TITLE
fork的问题

### ISSUE THREAD

**Issue by MW8023** [lxk0301/scripts#24]
大佬你好  我想问一下就好比之前一段时间fork你的代码，你会不时的更新，那我fork后的怎么更新呢

**Comment by DoveBoy** [comment]
pull request

**Comment by MW8023** [comment]
奇怪的是 我没有pull request 而是删除重新fork了 然后重新填了key啥的  actions就不运行了  不知道为啥呢

**Comment by lxk0301** [comment]
> 奇怪的是 我没有pull request 而是删除重新fork了 然后重新填了key啥的 actions就不运行了 不知道为啥呢

不运行？应该是没到cron时间

**Comment by MW8023** [comment]
我今天看了一下还是没有运行  应该不是corn时间的问题   我的多个cookie是用的&拼接的，应该也没什么问题，加了一个FruitShareCodes里面的内容就是一个京东水果的助力码，不知道哪里出了问题

**Comment by lxk0301** [comment]
> 我今天看了一下还是没有运行 应该不是corn时间的问题 我的多个cookie是用的&拼接的，应该也没什么问题，加了一个FruitShareCodes里面的内容就是一个京东水果的助力码，不知道哪里出了问题

// github action用户的好友互助码填写到Action->Settings->Secrets->new Secret里面(Name填写 FruitShareCodes(此处的Name必须按此来写,不能随意更改),内容处填写互助码,填写规则如下)
// 同一个京东账号的好友互助码用@符号隔开,不同京东账号之间按Cookie隔开方法,即用&符号隔开,下面给一个示例
// 如: 京东账号1的shareCode1@京东账号1的shareCode2&京东账号2的shareCode1@京东账号2的shareCode2

**Comment by MW8023** [comment]
那如果我这个添加错了  是影响到单单一个京东农场  还是整个脚本都运行不了呢  我现在的农场就是多个cookie一个助力码  那就是助力码@助力码。。。。是吗

**Comment by lxk0301** [comment]
> 那如果我这个添加错了 是影响到单单一个京东农场 还是整个脚本都运行不了呢 我现在的农场就是多个cookie一个助力码 那就是助力码@助力码。。。。是吗

多个ck  ，一个助力码 ， 那就是  助力码&助力码&助力码

**Comment by MW8023** [comment]
大佬  我把那个助力码改成用&分开了  可是actions还是没有一条结果呢  我之前还是好好的呢  就是重新fork你的代码再次设置cookie 助力码一些东西就不动了 cookie也是&分开的对吧

**Comment by lxk0301** [comment]
> 大佬 我把那个助力码改成用&分开了 可是actions还是没有一条结果呢 我之前还是好好的呢 就是重新fork你的代码再次设置cookie 助力码一些东西就不动了 cookie也是&分开的对吧

我怎么没看到你的github action有运行记录呢？  cookie还是之前的样子，用&隔开，

**Comment by MW8023** [comment]
没看到运行记录  是因为我之前不知道怎么更新你的代码  我就直接删除了  然后重新fork了  所以记录就没了

**Comment by lxk0301** [comment]
@MW8023  助力码的问题， 还是看你要什么助力。你如果是想第一个账号给三个码助力，就用@ （京东账号1助力-码1,码2码3）

如果是三个京东账号，给三个助力码助力，就用& （比如：京东1助力-码1，京东二助力-码2，京东3助力-码3）

宠汪汪兑换奖品是兑换到了，才会发通知， 没有兑换到，就不发通知

**Comment by MW8023** [comment]
> @MW8023  助力码的问题， 还是看你要什么助力。你如果是想第一个账号给三个码助力，就用@ （京东账号1助力-码1,码2码3）
> 
> 
> 
> 如果是三个京东账号，给三个助力码助力，就用& （比如：京东1助力-码1，京东二助力-码2，京东3助力-码3）
> 
> 
> 
> 宠汪汪兑换奖品是兑换到了，才会发通知， 没有兑换到，就不发通知

那如果我是多个京东账号一个助力码呢，就直接写一个就行了是吧。
通知的那个原来如此，明白了，感谢大佬

**Comment by lxk0301** [comment]
如果是三个京东账号，给同一个助力码助力，就用& （比如：京东1助力-码1，京东二助力-码1，京东3助力-码1）

**Comment by MW8023** [comment]
> 如果是三个京东账号，给同一个助力码助力，就用& （比如：京东1助力-码1，京东二助力-码1，京东3助力-码1）
是不是只能放三个，还是可以多个

**Comment by lxk0301** [comment]
> > 如果是三个京东账号，给同一个助力码助力，就用& （比如：京东1助力-码1，京东二助力-码1，京东3助力-码1）
> > 是不是只能放三个，还是可以多个

一个账号 ，最多助力4个不同的码

**Comment by MW8023** [comment]
> > > 如果是三个京东账号，给同一个助力码助力，就用& （比如：京东1助力-码1，京东二助力-码1，京东3助力-码1）
> 
> > > 是不是只能放三个，还是可以多个
> 
> 
> 
> 一个账号 ，最多助力4个不同的码

我现在是五个账号，一个助力码，就是助力码&助力码&助力码&助力码&助力码，对吧

**Comment by lxk0301** [comment]
> > > > 如果是三个京东账号，给同一个助力码助力，就用& （比如：京东1助力-码1，京东二助力-码1，京东3助力-码1）
> > 
> > 
> > > > 是不是只能放三个，还是可以多个
> > 
> > 
> > 一个账号 ，最多助力4个不同的码
> 
> 我现在是五个账号，一个助力码，就是助力码&助力码&助力码&助力码&助力码，对吧

对。
