### ISSUE TITLE
docker方式不适用与ecs用户？容器内ping不通外网

### ISSUE THREAD

**Issue by new-lcc** [lxk0301/scripts#240]

**Comment by iouAkira** [comment]
我用我的ecs测试没有问题，你需要提供更多信息才能排查问题
![image](https://user-images.githubusercontent.com/6993269/97397846-20d13d00-1925-11eb-8d38-2cc407dbbdd7.png)

**Comment by new-lcc** [comment]
[root@10-23-29-234 jd_scripts]# docker-compose up -d
Creating network "jd_scripts_default" with the default driver
Creating jd_scripts ... done
[root@10-23-29-234 jd_scripts]#
[root@10-23-29-234 jd_scripts]# docker exec -it jd_scripts /bin/sh
/scripts # ping baidu.com
ping: bad address 'baidu.com'
/scripts # ping 106.75.226.232
PING 106.75.226.232 (106.75.226.232): 56 data bytes
64 bytes from 106.75.226.232: seq=0 ttl=59 time=2.228 ms
64 bytes from 106.75.226.232: seq=1 ttl=59 time=1.184 ms
64 bytes from 106.75.226.232: seq=2 ttl=59 time=1.092 ms
64 bytes from 106.75.226.232: seq=3 ttl=59 time=1.011 ms
64 bytes from 106.75.226.232: seq=4 ttl=59 time=0.974 ms
^C
--- 106.75.226.232 ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 0.974/1.297/2.228 ms
/scripts # ping 220.181.38.148
PING 220.181.38.148 (220.181.38.148): 56 data bytes
64 bytes from 220.181.38.148: seq=0 ttl=45 time=28.282 ms
64 bytes from 220.181.38.148: seq=1 ttl=45 time=27.439 ms
64 bytes from 220.181.38.148: seq=2 ttl=45 time=27.376 ms
64 bytes from 220.181.38.148: seq=3 ttl=45 time=27.302 ms
64 bytes from 220.181.38.148: seq=4 ttl=45 time=27.361 ms
64 bytes from 220.181.38.148: seq=5 ttl=45 time=27.290 ms
64 bytes from 220.181.38.148: seq=6 ttl=45 time=27.355 ms
64 bytes from 220.181.38.148: seq=7 ttl=45 time=27.299 ms
^C
--- 220.181.38.148 ping statistics ---
8 packets transmitted, 8 packets received, 0% packet loss
round-trip min/avg/max = 27.290/27.463/28.282 ms
/scripts # ping jd.com
ping: bad address 'jd.com'
/scripts # ping 118.193.98.63
PING 118.193.98.63 (118.193.98.63): 56 data bytes
64 bytes from 118.193.98.63: seq=0 ttl=39 time=29.271 ms
64 bytes from 118.193.98.63: seq=1 ttl=39 time=28.902 ms
64 bytes from 118.193.98.63: seq=2 ttl=39 time=28.752 ms
64 bytes from 118.193.98.63: seq=3 ttl=39 time=28.465 ms
64 bytes from 118.193.98.63: seq=4 ttl=39 time=28.341 ms
^C
--- 118.193.98.63 ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 28.341/28.746/29.271 ms
/scripts #
/scripts # cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.20.0.2      fbf698f3dd6b
/scripts #
