### ISSUE TITLE
使用docker方式1，已经填写了微信server酱，但是没有收到任何推送，请问还有其他开关吗？

### ISSUE THREAD

**Issue by sysnxw** [lxk0301/scripts#246]
有如下设置。   
 #微信server酱
    - PUSH_KEY=SCU35246T99050**********************15bde5948c632a

**Comment by iouAkira** [comment]
没有其他开关，看日志里面通知那块提示的是什么

**Comment by sysnxw** [comment]
手动运行了水果，日志如下。

🔔东东农场, 开始!
开始获取配置文件


==================脚本执行来自 github action=====================

==================脚本执行-国际标准时间(UTC)：10/29/2020, 2:36:10 PM=====================

==================脚本执行- 北京时间(UTC+8)：10/29/2020, 10:36:10 PM=====================

共1个京东账号

jdFruitShareArr::["6fb07167e6ec4de8b10e07d1f1c8249b@ac497cee488f45639e2371d45d967003"]
jdFruitShareArr账号长度::1

开始【京东账号1】70719609-342523

第1个京东账号的助力码:::6fb07167e6ec4de8b10e07d1f1c8249b@ac497cee488f45639e2371d45d967003
格式化后第1个京东账号的助力码["6fb07167e6ec4de8b10e07d1f1c8249b","ac497cee488f45639e2371d45d967003"]

【您的互助码shareCode】 a15ae184e705405fb0c75a60876c36da


【已成功兑换水果】1次

开始助力好友
格式化后的助力码::["6fb07167e6ec4de8b10e07d1f1c8249b","ac497cee488f45639e2371d45d967003"]

开始助力京东账号1 - 70719609-342523的好友: 6fb07167e6ec4de8b10e07d1f1c8249b
【助力好友结果】: 好友【卢^_^珊々】已满五人助力
【今日助力次数还剩】2次

开始助力京东账号1 - 70719609-342523的好友: ac497cee488f45639e2371d45d967003
【助力好友结果】: 之前给【东方】助力过了
【今日助力次数还剩】2次

助力好友结束，即将开始领取额外水滴奖励


3斤苹果种植中...


初始化任务列表
开始签到
今天已签到,连续签到2,下次签到可得15g

被水滴砸中： 否
签到结束,开始广告浏览任务
今天已经做过浏览广告任务

当前不在定时领水时间断或者已经领过

给2个好友浇水任务已完成

接收邀请成为好友结果:{"type":"-inviteFriend","code":"17"}
对方已是您的好友
接收邀请成为好友结果:{"type":"-inviteFriend","code":"17"}
对方已是您的好友

今日已邀请好友0个 / 每日邀请上限10个
今日未邀请过好友
开始打卡领水活动（签到，关注，领券）
开始打卡领水活动（签到，关注，领券）结束

助力好友未达到5个
领取额外奖励水滴结束

4小时候免费赠送的抽奖机会已领取
浏览天天抽奖的第1个逛会场任务已完成
浏览天天抽奖的第2个逛会场任务已完成
浏览天天抽奖的第3个逛会场任务已完成
浏览天天抽奖的第4个逛会场任务已完成
浏览天天抽奖的第5个逛会场任务已完成
开始天天抽奖--好友助力--每人每天只有三次助力机会.
天天抽奖-助力卢^_^珊々失败,助力次数耗尽

---天天抽奖次数remainLotteryTimes----0次
天天抽奖--抽奖机会为0次

今日已完成10次浇水任务


初始化任务列表
首次浇水奖励已领取

finished 水果任务完成!

初始化任务列表
给好友浇水的25g水滴奖励已领取

小鸭子游戏达到上限
开始检查剩余水滴能否再次浇水再次浇水

剩余水滴107g

背包已有道具:
快速浇水卡:18张
水滴翻倍卡:未解锁
水滴换京豆卡:1张
加签卡:未解锁

目前剩余水滴：【107】g,不再继续浇水,保留部分水滴用于完成第二天【十次浇水得水滴】任务
开始预测水果成熟时间


初始化任务列表

【京东账号1】70719609-342523
【今日剩余助力👬】2次
【额外奖励】领取失败,原因：助力好友未达5个
【今日共浇水】18次
【剩余 水滴】107g💧
【水果🍉进度】86.25%，已浇水345次,还需55次
【预测】3天之后(2020-11-01日)可兑换水果🍉


🔔东东农场, 结束! 🕛 19.596 秒

**Comment by iouAkira** [comment]
正常情况下应该有这一块啊，方便截图看下你的 `docker-compose.yml` 文件，里面的 `environment`  这块的配置
![image](https://user-images.githubusercontent.com/6993269/97534543-28601700-19f5-11eb-8221-b91ec1134687.png)

**Comment by sysnxw** [comment]
找到原因了，是我制作聪明，添加了如下内容，反而实效。删除就可以收到推送了。
不过话说回来，就是之前收不到推送，我才加上如下内容的`...
========
    #通知开关
    - PET_NOTIFY_CONTROL=true
    - FRUIT_NOTIFY_CONTROL=true
    - JD_JOY_REWARD_NOTIFY=true
    - MARKET_REWARD_NOTIFY=true
    - JD_818_SHAREID_NOTIFY=true

========
