### ISSUE TITLE
狂欢城API错误

### ISSUE THREAD

**Issue by leecheng310** [lxk0301/scripts#248]
逛新品获得积分:0
逛新品获得京豆:0
逛店铺获得积分:0
逛店铺获得京豆:0
逛会场--获得积分:0
逛会场--获得京豆:0
逛新品获得积分:0
逛新品获得京豆:0
逛店铺获得积分:0
逛店铺获得京豆:0
逛会场--获得积分:0
逛会场--获得京豆:0
脚本自带助力码数量:6
是否大于当天九点🕘:true
"Response code 524 (Origin Time-out)"
京东手机狂欢城 API请求失败，请检查网路重试
printAPI返回助力码数量:1
累计助力码数量:7
去重后总助力码数量:7
助力结果:{"code":200,"msg":"成功","data":{"jdNums":0,"status":4}}
助力结果:{"code":200,"msg":"成功","data":{"jdNums":0,"status":4}}
助力结果:{"code":200,"msg":"成功","data":{"jdNums":0,"status":4}}
助力结果:{"code":200,"msg":"成功","data":{"jdNums":0,"status":4}}
助力结果:{"code":200,"msg":"成功","data":{"jdNums":0,"status":4}}
助力结果:{"code":200,"msg":"成功","data":{"jdNums":0,"status":4}}
助力结果:{"code":1005,"data":{},"msg":"活动已结束"}

这是什么原因，好像并不影响大部分豆子获得

**Comment by lxk0301** [comment]
@leecheng310 你那边超时

**Comment by leecheng310** [comment]
网络问题么·

**Comment by leecheng310** [comment]
不是通过云端走的么··这个失败是影响到哪个任务·

**Comment by lxk0301** [comment]
@leecheng310 不影响。有个API有问题你忽略就行
