### ISSUE TITLE
大佬能出个云函数教程不

### ISSUE THREAD

**Issue by lonma** [lxk0301/scripts#25]
大佬能出个云函数教程不

**Comment by lxk0301** [comment]
> 大佬能出个云函数教程不

腾讯云函数吗？我readme里面有写了一下粗略教程

**Comment by lonma** [comment]
是的，tx云函数，没看懂，不会改scf入口函数

**Comment by lonma** [comment]
大佬，这个脚本能移植到openwrt 的luci里签到不？直接编译一个openwrt 装入红米路由器自动签到就更好了

**Comment by lxk0301** [comment]
> 移植到openwrt 的luci里

这个 什么 移植到openwrt 的luci里 ，我真不会， 帮不了你， 你如果会的话， 可以尝试一下

**Comment by lonma** [comment]
我也不会，大佬麻烦出个详细腾讯云教程吧，谢谢，菜鸟本鸟只会照着改cookie ，话说cookie 也是要新建一个js文本么

**Comment by lxk0301** [comment]
> 我也不会，大佬麻烦出个详细腾讯云教程吧，谢谢，菜鸟本鸟只会照着改cookie ，话说cookie 也是要新建一个js文本么

不能， 没空。 要注意的地方，我已经在readme里面写出来了， 其他基础的用法，你自行网上搜索解决。jdCookie.js文件是必须要的

**Comment by DoveBoy** [comment]
> > 我也不会，大佬麻烦出个详细腾讯云教程吧，谢谢，菜鸟本鸟只会照着改cookie ，话说cookie 也是要新建一个js文本么
> 
> 不能， 没空。 要注意的地方，我已经在readme里面写出来了， 其他基础的用法，你自行网上搜索解决。jdCookie.js文件是必须要的

借层问个问题，目前想试试云函数跑，单个js脚本跑起来已经成功了，如果需要同时跑多个js怎么写index.js里面的内容？

'use strict';
exports.main_handler = async (event, context, callback) => {
    require('./jd_speed.js')
}

require里面如果需要运行多个js，格式怎么写？

**Comment by lxk0301** [comment]
@DoveBoy 重新新建一个空白函数吧。

**Comment by lonma** [comment]
Dove 大佬出个教程，一起学习下

**Comment by DoveBoy** [comment]
> @DoveBoy 重新新建一个空白函数吧。

😭😭😭，那样要建好多函数，每跑一个js就需要为此建一个单独函数。只能这样了吗？Google好久没找到有用的方法

**Comment by DoveBoy** [comment]
> Dove 大佬出个教程，一起学习下

项目开发者在readme里面已经写得很明了了，关键步骤都写了，按照说明写就能构建完成

**Comment by lonma** [comment]
> > Dove 大佬出个教程，一起学习下
> 
> 项目开发者在readme里面已经写得很明了了，关键步骤都写了，按照说明写就能构建完成

依赖是传package.json还是node.modules？
