### ISSUE TITLE
京豆变动无限循环

### ISSUE THREAD

**Issue by HeatonZ** [lxk0301/scripts#250]
最近都没有京豆收入的号无限循环了

第132页: {"code":"0","detailList":[]}
第133页: {"code":"0","detailList":[]}
第134页: {"code":"0","detailList":[]}
第135页: {"code":"0","detailList":[]}
第136页: {"code":"0","detailList":[]}
第137页: {"code":"0","detailList":[]}
第138页: {"code":"0","detailList":[]}
第139页: {"code":"0","detailList":[]}

**Comment by lxk0301** [comment]
@HeatonZ 收到 ，bug

**Comment by lxk0301** [comment]
你这个号是不是有问题, 按理说京东不会返回空的数据的

**Comment by HeatonZ** [comment]
> 你这个号是不是有问题, 按理说京东不会返回空的数据的

刚刚运行一小时了，因为是很久没上线的号。运行两天应该就没这个问题了。
