### ISSUE TITLE
最新的镜像，执行jd_bean_sign。报错。

### ISSUE THREAD

**Issue by sysnxw** [lxk0301/scripts#251]
其他脚本正常，麻烦看看，多谢。

====================共有1个京东账号Cookie=========

==================脚本执行来自 github action=====================

==================脚本执行-国际标准时间(UTC)：10/29/2020, 8:59:00 PM=====================

==================脚本执行- 北京时间(UTC+8)：10/30/2020, 4:59:00 AM=====================

开始京东账号1 70719609-342523京豆签到

替换变量完毕
执行完毕北京时间：2020-10-30

server酱发送通知消息成功

找不到 Key 对应的 DeviceToken, 请确保 Key 正确! Key 可在 App 端注册获得。

telegram发送通知消息失败！！

HTTPError: Response code 404 (Not Found)
    at Request.<anonymous> (/scripts/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined,
  timings: {
    start: 1603976353936,
    socket: 1603976353936,
    lookup: 1603976353937,
    connect: 1603976354180,
    secureConnect: 1603976354426,
    upload: 1603976354426,
    response: 1603976354685,
    end: 1603976354686,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 1,
      tcp: 243,
      tls: 246,
      request: 0,
      firstByte: 259,
      download: 1,
      total: 750
    }
  }
}

token is not exist

您未提供iGot的推送IGOT_PUSH_KEY，取消iGot推送消息通知

运行完成后，删除下载的文件

京东账号1 70719609-342523京豆签到完成

🔔京豆签到, 开始!

🔔京豆签到, 结束! 🕛 14.821 秒

**Comment by sysnxw** [comment]
这是server酱推送内容。
=======================
Warning: mysqli_connect() [function.mysqli-connect]: (08004/1040): Too many connections in _lp/core/lib/db.sae.mysqli.function.php on line 20
can't connect to database
Fatal error: Uncaught exception 'Exception' with message ' is not SocketLog method' in /data1/www/htdocs/365/anime/2/lib/SocketLog.class.php:33 Stack trace: #0 /data1/www/htdocs/365/anime/2/_lp/core/lib/db.sae.mysqli.function.php(131): slog('SELECT * FROM `...', false) #1 /data1/www/htdocs/365/anime/2/_lp/core/lib/db.sae.mysqli.function.php(155): get_data('SELECT * FROM `...', NULL) #2 /data1/www/htdocs/365/anime/2/controller/wechat.class.php(426): get_line('SELECT * FROM `...') #3 [internal function]: wechatController->read_login('043L5c0w3ZtjdV2...', 225957557) #4 /data1/www/htdocs/365/anime/2/_lp/lp.init.php(94): ReflectionMethod->invokeArgs(Object(wechatController), Array) #5 /data1/www/htdocs/365/anime/2/index.php(28): include_once('/data1/www/htdo...') #6 {main} thrown in lib/SocketLog.class.php on line 33

**Comment by iouAkira** [comment]
@sysnxw tg通知 不用的话 删掉 TG_BOT_TOKEN 和 TG_USER_ID 两行

**Comment by lxk0301** [comment]
@sysnxw 你提供了bark app的推送通知token。但是他不对。tg机器人通知你也提供了。但是也不对

**Comment by sysnxw** [comment]
多谢。我没有提供这些呢~我删除先试试。
=====
    #微信server酱
    - PUSH_KEY=SCU35246T990504*****************************32a
    #Bark App通知
    - BARK_PUSH=""
    #telegram机器人通知
    - TG_BOT_TOKEN=""
    - TG_USER_ID=""
    #钉钉机器人通知
    - DD_BOT_TOKEN=""
    - DD_BOT_SECRET=""
    #京东种豆得豆

**Comment by sysnxw** [comment]
删除后问题解决，多谢。

**Comment by sysnxw** [comment]
但是同样的配置，只有jd_bean_sign报错，其他都正常。有点奇怪。

**Comment by zing518** [comment]
东东农场：e05ac5f5794e42b48a429cfd6a25d8d9
东东萌宠：MTAxODc2NTEzNTAwMDAwMDAyMzE2NjMwNQ==
种豆得豆：yrij55f7gfgokaj5ecrxtxgav4
