### ISSUE TITLE
大佬，我用的github actions，刚刚突然提示我所有workflow全被关了，还说是手动关的这是啥情况啊

### ISSUE THREAD

**Issue by 627992512** [lxk0301/scripts#253]
![Screenshot_20201030_030104_com tencent androidqqmail](https://user-images.githubusercontent.com/57834276/97620403-7e1bda00-1a5c-11eb-8761-77702db2e00f.jpg)

**Comment by JohnED512** [comment]
去Acition里挨个enable就行了

**Comment by 627992512** [comment]
嗯嗯，谢谢啊，不过这个我已经知道了。我就是想问一下为什么会出现这种情况，有没有办法避免这种情况，要是每次都要重新enable的话还是有点麻烦。（老懒狗了）

**Comment by chen1006** [comment]
我的也是、这是什么情况

**Comment by MisterGlasses** [comment]
同

**Comment by lxk0301** [comment]
暂无方法一次性全部开启, 自己一个一个手动开启吧

**Comment by MisterGlasses** [comment]
> 暂无方法一次性全部开启, 自己一个一个手动开启吧

复制项目的好像没事

**Comment by 627992512** [comment]
> 暂无方法一次性全部开启, 自己一个一个手动开启吧

好的好的

**Comment by wheatwee** [comment]
我也想知道为什么会这样，好像很多人都出现这个问题了

**Comment by 18553123709** [comment]
目测是官方关的，我这个号的另外一个仓库的actions也全被关了，但另外一个小号的script仓库里的workflow只被关了一半，就很迷

**Comment by 09wqlin** [comment]
小白求教各位大佬，在action里有显示同步了脚本库文件，但是在自己code里显示的脚本还是原来那样，请问这样是更新了没有

**Comment by lxk0301** [comment]
> 小白求教各位大佬，在action里有显示同步了脚本库文件，但是在自己code里显示的脚本还是原来那样，请问这样是更新了没有

看了你fork后的。是同步了最新代码

**Comment by hupo376787** [comment]
Gayhub好像发现了不对劲🤣
