### ISSUE TITLE
大佬，我用的github actions,有配置项关闭自动取关么?

### ISSUE THREAD

**Issue by enews** [lxk0301/scripts#256]
我的关注列表里面有很多关注, 每次自动取关都会把我的关注删除掉一部分,导致越来越少, 有某个配置项可以设置遇到某个商品后停止取关么? 或者关闭自动取关功能

**Comment by JKamiy** [comment]
disable jd_unsubscribe  这个workflow即可

**Comment by enews** [comment]
> 
> 
> disable jd_unsubscribe 这个workflow即可

感谢

**Comment by lxk0301** [comment]
@enews 看教程里面的secret集合, 或者禁用这个脚本
