### ISSUE TITLE
签到错误，有没有遇到同样问题的，是我网络的原因吗？

### ISSUE THREAD

**Issue by jk9527** [lxk0301/scripts#258]
京豆签到, 错误!
RequestError: connect ECONNREFUSED 151.101.228.133:443
at ClientRequest.req.once.err (/scripts/node_modules/download/node_modules/got/index.js:182:22)
at Object.onceWrapper (events.js:286:20)
at ClientRequest.emit (events.js:198:13)
at TLSSocket.socketErrorListener (_http_client.js:401:9)
at TLSSocket.emit (events.js:198:13)
at emitErrorNT (internal/streams/destroy.js:91:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
at process._tickCallback (internal/process/next_tick.js:63:19)

手动多试几次又能成功，有知道这个ip是干什么的吗？

**Comment by lxk0301** [comment]
你这是什么运行环境?

提示是说拒绝错误的连接请求

**Comment by iouAkira** [comment]
应该是GitHub的IP，配置一下环境变量 ` CDN_JD_DAILYBONUS=true` 试试吧

**Comment by jk9527** [comment]
https://github.com/chinnkarahoi/jd-scripts-docker 
用的这个docker教程，手动多执行几次签到又能成功。

**Comment by jk9527** [comment]
> 应该是GitHub的IP，配置一下环境变量 ` CDN_JD_DAILYBONUS=true` 试试吧

大佬，docker中这个怎么配置？

**Comment by iouAkira** [comment]
> > 应该是GitHub的IP，配置一下环境变量 ` CDN_JD_DAILYBONUS=true` 试试吧
> 
> 大佬，docker中这个怎么配置？

`docker-compose.yml` 里面 配置在  `environment` 下面

**Comment by jk9527** [comment]
> environment

 jd1:
    <<: [ *logger, *common ]
    container_name: jd1
    volumes:
      - ./env/all:/all
      - ./env/env1:/env
     environment：CDN_JD_DAILYBONUS=true
 jd2:
    <<: [ *logger, *common ]
    container_name: jd2
    volumes:
      - ./env/all:/all
      - ./env/env2:/env
    environment：CDN_JD_DAILYBONUS=true

这样吗？

**Comment by jk9527** [comment]
> > > 应该是GitHub的IP，配置一下环境变量 ` CDN_JD_DAILYBONUS=true` 试试吧
> > 
> > 
> > 大佬，docker中这个怎么配置？
> 
> `docker-compose.yml` 里面 配置在 `environment` 下面

jd1:
<<: [ *logger, *common ]
container_name: jd1
volumes:
- ./env/all:/all
- ./env/env1:/env
environment：CDN_JD_DAILYBONUS=true
jd2:
<<: [ *logger, *common ]
container_name: jd2
volumes:
- ./env/all:/all
- ./env/env2:/env
environment：CDN_JD_DAILYBONUS=true

这样吗？

**Comment by iouAkira** [comment]
> > > > 应该是GitHub的IP，配置一下环境变量 ` CDN_JD_DAILYBONUS=true` 试试吧
> > > 
> > > 
> > > 大佬，docker中这个怎么配置？
> > 
> > 
> > `docker-compose.yml` 里面 配置在 `environment` 下面
> 
> jd1:
> <<: [ *logger, *common ]
> container_name: jd1
> volumes:
> 
> * ./env/all:/all
> * ./env/env1:/env
>   environment：CDN_JD_DAILYBONUS=true
>   jd2:
>   <<: [ *logger, *common ]
>   container_name: jd2
>   volumes:
> * ./env/all:/all
> * ./env/env2:/env
>   environment：CDN_JD_DAILYBONUS=true
> 
> 这样吗？

[参考这里](https://github.com/lxk0301/scripts/tree/master/docker#%E5%88%9B%E5%BB%BA%E4%B8%80%E4%B8%AA%E7%9B%AE%E5%BD%95jd_scripts%E7%94%A8%E4%BA%8E%E5%AD%98%E6%94%BE%E5%A4%87%E4%BB%BD%E9%85%8D%E7%BD%AE%E7%AD%89%E6%95%B0%E6%8D%AE%E8%BF%81%E7%A7%BB%E9%87%8D%E8%A3%85%E7%9A%84%E6%97%B6%E5%80%99%E5%8F%AA%E9%9C%80%E8%A6%81%E5%A4%87%E4%BB%BD%E6%95%B4%E4%B8%AAjd_scripts%E7%9B%AE%E5%BD%95%E5%8D%B3%E5%8F%AF)

**Comment by jk9527** [comment]
> * environment：CDN_JD_DAILYBONUS=true



> > > > > 应该是GitHub的IP，配置一下环境变量 ` CDN_JD_DAILYBONUS=true` 试试吧
> > > > 
> > > > 
> > > > 大佬，docker中这个怎么配置？
> > > 
> > > 
> > > `docker-compose.yml` 里面 配置在 `environment` 下面
> > 
> > 
> > jd1:
> > <<: [ *logger, *common ]
> > container_name: jd1
> > volumes:
> > 
> > * ./env/all:/all
> > * ./env/env1:/env
> >   environment：CDN_JD_DAILYBONUS=true
> >   jd2:
> >   <<: [ *logger, *common ]
> >   container_name: jd2
> >   volumes:
> > * ./env/all:/all
> > * ./env/env2:/env
> >   environment：CDN_JD_DAILYBONUS=true
> > 
> > 这样吗？
> 
> [参考这里](https://github.com/lxk0301/scripts/tree/master/docker#%E5%88%9B%E5%BB%BA%E4%B8%80%E4%B8%AA%E7%9B%AE%E5%BD%95jd_scripts%E7%94%A8%E4%BA%8E%E5%AD%98%E6%94%BE%E5%A4%87%E4%BB%BD%E9%85%8D%E7%BD%AE%E7%AD%89%E6%95%B0%E6%8D%AE%E8%BF%81%E7%A7%BB%E9%87%8D%E8%A3%85%E7%9A%84%E6%97%B6%E5%80%99%E5%8F%AA%E9%9C%80%E8%A6%81%E5%A4%87%E4%BB%BD%E6%95%B4%E4%B8%AAjd_scripts%E7%9B%AE%E5%BD%95%E5%8D%B3%E5%8F%AF)

感谢大佬，加了后删了容器重新添加，签到正常了
