### ISSUE TITLE
大佬，星推官没有加京豆

### ISSUE THREAD

**Issue by xiaoyanzi1991** [lxk0301/scripts#262]
大佬，我的星推官脚本看起来是执行了的，但是就是一直没有得到京豆，我看我朋友的每天从星推官来的京豆就是好几百，这是怎么回事呢？

**Comment by lxk0301** [comment]
...........

 活动时间：2020年10月21日 00:00:00-2020年11月12日 23:59:59
 京豆先到先得！！！！！！！！！！

要不就是运行脚本的时间晚了， 要不就是你自己账号有问题

**Comment by xiaoyanzi1991** [comment]
好的，我去看看脚本时间~谢谢大佬~~~~
