### ISSUE TITLE
群晖下 直接compose部署，定时任务不执行

### ISSUE THREAD

**Issue by dreammis** [lxk0301/scripts#264]
我这边问起和[https://github.com/lxk0301/scripts/issues/186](https://github.com/lxk0301/scripts/issues/186) 这位兄台的差不多

我折腾了许久，直接进容器里是执行是没问题的。
crontab file 指定 用户，指定node路径均无效

好奇怪，docker logs 又是可以看到定时任务是触发了。

但是就是没执行。
![image](https://user-images.githubusercontent.com/12542216/97680194-4602ae80-1ad1-11eb-9215-f6473ca86874.png)

我用其他物理机docker部署好像又没什么问题

怀疑是群晖这个宿主机和这个容器有什么猫腻。

搞不懂，也有可能是alpine的crond有问题。

我现在尝试自己打包一个alpine:3.9试一试

有其他同样情况的小伙伴吗。

**Comment by dreammis** [comment]
最后在宿主机的crontab中加入了。

这样有个缺点自动化不够。

在群晖宿主机的/etc/crontab 文件中添加

0 */1 * * * root docker exec jd_scripts sh -c 'git -C /scripts/ pull >> /scripts/logs/pull.log 2>&1'
0 0-18/6 * * * root docker exec jd_scripts sh -c 'node /scripts/jd_818.js >> /scripts/logs/jd_818.log 2>&1'
0,10 0 * * * root docker exec jd_scripts sh -c 'node /scripts/jd_xtg.js >> /scripts/logs/jd_xtg.log 2>&1'
*/1 * * * * root docker exec jd_scripts sh -c 'node /scripts/jd_bean_sign.js >> /scripts/logs/jd_bean_sign.log 2>&1'
0 0 * * * root docker exec jd_scripts sh -c 'node /scripts/jd_blueCoin.js >> /scripts/logs/jd_blueCoin.log 2>&1'
0 0 * * * root docker exec jd_scripts sh -c 'node /scripts/jd_club_lottery.js >> /scripts/logs/jd_club_lottery.log 2>&1'
5 6-18/6 * * * root docker exec jd_scripts sh -c 'node /scripts/jd_fruit.js >> /scripts/logs/jd_fruit.log 2>&1'
15 */2 * * * root docker exec jd_scripts sh -c 'node /scripts/jd_joy.js >> /scripts/logs/jd_joy.log 2>&1'
15 */1 * * * root docker exec jd_scripts sh -c 'node /scripts/jd_joy_feedPets.js >> /scripts/logs/jd_joy_feedPets.log 2>&1'
0 0-16/8 * * * root docker exec jd_scripts sh -c 'node /scripts/jd_joy_reward.js >> /scripts/logs/jd_joy_reward.log 2>&1'
0 0,6 * * * root docker exec jd_scripts sh -c 'node /scripts/jd_joy_steal.js >> /scripts/logs/jd_joy_steal.log 2>&1'
0 */2 * * * root docker exec jd_scripts sh -c 'node /scripts/jd_moneyTree.js >> /scripts/logs/jd_moneyTree.log 2>&1'
5 6-18/6 * * * root docker exec jd_scripts sh -c 'node /scripts/jd_pet.js >> /scripts/logs/jd_pet.log 2>&1'
0 7-21/2 * * * root docker exec jd_scripts sh -c 'node /scripts/jd_plantBean.js >> /scripts/logs/jd_plantBean.log 2>&1'
1 1 * * * root docker exec jd_scripts sh -c 'node /scripts/jd_redPacket.js >> /scripts/logs/jd_redPacket.log 2>&1'
10 0 * * * root docker exec jd_scripts sh -c 'node /scripts/jd_shop.js >> /scripts/logs/jd_shop.log 2>&1'
8 */3 * * * root docker exec jd_scripts sh -c 'node /scripts/jd_speed.js >> /scripts/logs/jd_speed.log 2>&1'
11 1-23/5 * * * root docker exec jd_scripts sh -c 'node /scripts/jd_superMarket.js >> /scripts/logs/jd_superMarket.log 2>&1'
55 23 * * * root docker exec jd_scripts sh -c 'node /scripts/jd_unsubscribe.js >> /scripts/logs/jd_unsubscribe.log 2>&1'
0 */1 * * * root docker exec jd_scripts sh -c 'node /scripts/jd_collectProduceScore.js >> /scripts/logs/jd_collectProduceScore.log 2>&1'
0 2 * * * root docker exec jd_scripts sh -c 'node /scripts/jd_bean_change.js >> /scripts/logs/jd_bean_change.log 2>&1'

**Comment by iouAkira** [comment]
> 我这边问起和#186 这位兄台的差不多
> 
> 我折腾了许久，直接进容器里是执行是没问题的。
> crontab file 指定 用户，指定node路径均无效
> 
> 好奇怪，docker logs 又是可以看到定时任务是触发了。
> 
> 但是就是没执行。
> ![image](https://user-images.githubusercontent.com/12542216/97680194-4602ae80-1ad1-11eb-9215-f6473ca86874.png)
> 
> 我用其他物理机docker部署好像又没什么问题
> 
> 怀疑是群晖这个宿主机和这个容器有什么猫腻。
> 
> 搞不懂，也有可能是alpine的crond有问题。
> 
> 我现在尝试自己打包一个alpine:3.9试一试
> 
> 有其他同样情况的小伙伴吗。

我也是群晖，没法重现你们这个问题，他们有问题的文件直接给我导入进去也是没问题的😂

**Comment by luvsicz** [comment]
借楼问一下 @iouAkira ,大佬写的docker-compose方法，取消订阅的配置要怎么填写呀？我试过换行 逗号分隔  双引号\n  脚本都识别不了这个参数。
` #取关设置
    - UN_SUBSCRIBES=40,40,iPhone12,Apple京东自营旗舰店`

**Comment by iouAkira** [comment]
> 借楼问一下 @iouAkira ,大佬写的docker-compose方法，取消订阅的配置要怎么填写呀？我试过换行 逗号分隔 双引号\n 脚本都识别不了这个参数。
> ` #取关设置 - UN_SUBSCRIBES=40,40,iPhone12,Apple京东自营旗舰店`

`- UN_SUBSCRIBES=40\n40\niPhone12\nApple京东自营旗舰店` 应该是没问题的

**Comment by iouAkira** [comment]
> > 借楼问一下 @iouAkira ,大佬写的docker-compose方法，取消订阅的配置要怎么填写呀？我试过换行 逗号分隔 双引号\n 脚本都识别不了这个参数。
> > ` #取关设置 - UN_SUBSCRIBES=40,40,iPhone12,Apple京东自营旗舰店`
> 
> `- UN_SUBSCRIBES=40\n40\niPhone12\nApple京东自营旗舰店` 这样应该是没问题的

我看脚本里面取到的好像加了转译  @lxk0301 有办法处理么😂
![image](https://user-images.githubusercontent.com/6993269/97771365-fb3b7200-1b76-11eb-963b-901be03c6f41.png)

**Comment by lxk0301** [comment]
> > > 借楼问一下 @iouAkira ,大佬写的docker-compose方法，取消订阅的配置要怎么填写呀？我试过换行 逗号分隔 双引号\n 脚本都识别不了这个参数。
> > > ` #取关设置 - UN_SUBSCRIBES=40,40,iPhone12,Apple京东自营旗舰店`
> > 
> > 
> > `- UN_SUBSCRIBES=40\n40\niPhone12\nApple京东自营旗舰店` 这样应该是没问题的
> 
> 我看脚本里面取到的好像加了转译 @lxk0301 有办法处理么😂
> ![image](https://user-images.githubusercontent.com/6993269/97771365-fb3b7200-1b76-11eb-963b-901be03c6f41.png)

咦，居然你们这边变成了两个\n，那我等会提供另外一种分割方式吧，\n或者&符合隔开

**Comment by dreammis** [comment]
> > 我这边问起和#186 这位兄台的差不多
> > 我折腾了许久，直接进容器里是执行是没问题的。
> > crontab file 指定 用户，指定node路径均无效
> > 好奇怪，docker logs 又是可以看到定时任务是触发了。
> > 但是就是没执行。
> > ![image](https://user-images.githubusercontent.com/12542216/97680194-4602ae80-1ad1-11eb-9215-f6473ca86874.png)
> > 我用其他物理机docker部署好像又没什么问题
> > 怀疑是群晖这个宿主机和这个容器有什么猫腻。
> > 搞不懂，也有可能是alpine的crond有问题。
> > 我现在尝试自己打包一个alpine:3.9试一试
> > 有其他同样情况的小伙伴吗。
> 
> ~我也是群晖，没法重现你们这个问题，他们有问题的文件直接给我导入进去也是没问题的😂~
> 搞错了我以为你用的docker1

是docker1 ，我在其他电脑上没问题，就在群晖里compose直接部有问题

**Comment by iouAkira** [comment]
docker1 里面没有这写东西啊，
![image](https://user-images.githubusercontent.com/6993269/97771902-9e42ba80-1b7c-11eb-9dea-a385de7539d6.png)

**Comment by dreammis** [comment]
> docker1 里面没有这写东西啊，
> ![image](https://user-images.githubusercontent.com/6993269/97771902-9e42ba80-1b7c-11eb-9dea-a385de7539d6.png)

这个是我自己改的，我怀疑是node执行有问题，直接换成sh脚本执行。结果还是不行。

**Comment by lxk0301** [comment]
@iouAkira @dreammis @luvsicz @smilingpoplar  刚才取关脚本的问题,我这边已做兼容, 你们谁更新一下上游仓库脚本,帮忙测试一下? 

换行以及`&` 以及docker被转义后的`\\n`都行

**Comment by luvsicz** [comment]
> @iouAkira @dreammis @luvsicz @smilingpoplar 刚才取关脚本的问题,我这边已做兼容, 你们谁更新一下上游仓库脚本,帮忙测试一下?
> 
> 换行以及`&` 以及docker被转义后的`\\n`都行

我国内机子现在pull GH失败了，我更新成功并测试再来回复吧

**Comment by iouAkira** [comment]
> @iouAkira @dreammis @luvsicz @smilingpoplar 刚才取关脚本的问题,我这边已做兼容, 你们谁更新一下上游仓库脚本,帮忙测试一下?
> 
> 换行以及`&` 以及docker被转义后的`\\n`都行

两种都OK了
![image](https://user-images.githubusercontent.com/6993269/97773220-ef58ab80-1b88-11eb-91f1-f4a6b8d89213.png)
![image](https://user-images.githubusercontent.com/6993269/97773241-0ac3b680-1b89-11eb-80ff-15b2bf80af9f.png)

**Comment by lxk0301** [comment]
> > @iouAkira @dreammis @luvsicz @smilingpoplar 刚才取关脚本的问题,我这边已做兼容, 你们谁更新一下上游仓库脚本,帮忙测试一下?
> > 换行以及`&` 以及docker被转义后的`\\n`都行
> 
> 两种都OK了
> ![image](https://user-images.githubusercontent.com/6993269/97773220-ef58ab80-1b88-11eb-91f1-f4a6b8d89213.png)
> ![image](https://user-images.githubusercontent.com/6993269/97773241-0ac3b680-1b89-11eb-80ff-15b2bf80af9f.png)

好的 ,多谢反馈

**Comment by jjss520** [comment]
大佬，我的jd_bean_sign.js还是不行，在窗口里重新安装了模块request，现在定时还是异常，手动没问题，就这一个脚本这样，也不知道什么原因

**Comment by iouAkira** [comment]
> 大佬，我的jd_bean_sign.js还是不行，在窗口里重新安装了模块request，现在定时还是异常，手动没问题，就这一个脚本这样，也不知道什么原因

拉最新的镜像，然后重建容器。或者窗口执行  `docker exec -it jd_scripts /bin/sh -c 'cd ~ && npm install request'`

**Comment by jjss520** [comment]
> > 大佬，我的jd_bean_sign.js还是不行，在窗口里重新安装了模块request，现在定时还是异常，手动没问题，就这一个脚本这样，也不知道什么原因
> 
> 拉最新的镜像，然后重建容器。或者窗口执行 `docker exec -it jd_scripts /bin/sh -c 'cd ~ && npm install request'`

删了原来的容器，更新镜像，新建容器，现在签到正常了
