### ISSUE TITLE
fork仓的github action执行的脚本还是来自大佬仓

### ISSUE THREAD

**Issue by makelage** [lxk0301/scripts#274]
yml 里git clone https://github.com/lxk0301/scripts.git
这里已经定了下载的脚本是原仓吧，
修改自己仓里的配置不生效，是需要逐个修改yml吗？
boxjs里也指定了好多"repo"

**Comment by lxk0301** [comment]
> yml 里git clone https://github.com/lxk0301/scripts.git
> 这里已经定了下载的脚本是原仓吧，
> 修改自己仓里的配置不生效，是需要逐个修改yml吗？
> boxjs里也指定了好多"repo"

是，如果需要自己修改，可以添加给定的secret。


boxjs里也指定了好多"repo"指的是什么？

**Comment by lxk0301** [comment]
目的是可以永远执行我仓库的最新脚本。目前需要自定义的已经提供了secret来控制

**Comment by makelage** [comment]
看了下代码，是需要secret来控制
