### ISSUE TITLE
定时执行的随机延迟

### ISSUE THREAD

**Issue by duandaxei** [lxk0301/scripts#275]
#238  
比如 818 的 workflows 麻烦 @lxk0301 大佬看下

      - name: '运行 【手机狂欢城脚本】'
        run: |
          random_time=$(($RANDOM % 59))
          echo "等待 ${random_time} 分钟后开始签到"
          for((i=1; i<=${random_time}; i++));
          do
            echo "倒计时 $[${random_time}-$i] 分钟"
            sleep 1m
          done
          cd ~/scripts
          node jd_818.js

**Comment by duandaxei** [comment]
![QQ截图20201031103719](https://user-images.githubusercontent.com/4309411/97769358-1bfacc00-1b65-11eb-9f63-545a40b1a683.jpg)
这个应该是可以的哈 麻烦大佬了

**Comment by lxk0301** [comment]
厉害，居然可以实现。还有 random_time=$(($RANDOM % 59)) 这句话是取随机数0-59之间的数字吗？

不过action本身就会存在延迟的问题😂😂。就是比如设置cron 9:00执行，可能要延迟一会才行。

所以觉得 https://github.com/lxk0301/scripts/issues/238 这个问题是有点过于忧虑了，每个人应该不会统一时间运行。

**Comment by duandaxei** [comment]
% 取余数嘛  是的
不过加一个 心理还是好受些 😆

**Comment by duandaxei** [comment]
![QQ截图20201031111012](https://user-images.githubusercontent.com/4309411/97769928-cbd23880-1b69-11eb-8837-8610b4200210.jpg)
![QQ截图20201031111039](https://user-images.githubusercontent.com/4309411/97769930-d5f43700-1b69-11eb-9cdb-edf40d128531.jpg)

**Comment by duandaxei** [comment]
> 厉害，居然可以实现。还有 random_time=$(($RANDOM % 59)) 这句话是取随机数0-59之间的数字吗？
> 
> 不过action本身就会存在延迟的问题😂😂。就是比如设置cron 9:00执行，可能要延迟一会才行。
> 
> 所以觉得 #238 这个问题是有点过于忧虑了，每个人应该不会统一时间运行。

记得好像是从 @peng4740 这个大佬那偷师来的 😆
