### ISSUE TITLE
关于共享码的一点建议

### ISSUE THREAD

**Issue by zhuzf88** [lxk0301/scripts#281]
能不能建立一个群，大家共享自己的sharecode。然后由作者加入脚本，随机抽取进行互助。

**Comment by 282206796** [comment]
同意

**Comment by tanst** [comment]
然后京东进来批量拉黑，太方便了，哈哈^_^

**Comment by dick1391** [comment]
哈哈

**Comment by zhuzf88** [comment]
> 然后京东进来批量拉黑，太方便了，哈哈^_^

你是不知道secrets吗？

**Comment by zhuzf88** [comment]
> 然后京东进来批量拉黑，太方便了，哈哈^_^

你是不知道现在里面就有很多共享码吗

**Comment by lxk0301** [comment]
不考虑此种方式. 需要我经常更新互助码
