### ISSUE TITLE
关于执行结果问题

### ISSUE THREAD

**Issue by 1021030435** [lxk0301/scripts#284]
不清楚运行的结果  看日志啥都没报 定时任务是跑了 到JD上看看树还是那样狗也是那样 咋回事呢- -

**Comment by anysoft** [comment]
看你用什么跑的
如果github Action应该没啥问题

腾讯云函数 需要手动本地下载依赖后全量上传，在线依赖会有兼容问题

本地跑如果用 crontab触发必须注意环境变量
crontab环境变量不是系统的环境变量，这个百度有解决方案 
0 0 * * * . /etc/profile; cd /scripts/  && node jd_speed.js

**Comment by 1021030435** [comment]
我本地搭建的centos 下次有空折腾下github action 图个乐呵



---原始邮件---
发件人: "anysoft"<notifications@github.com&gt;
发送时间: 2020年10月31日(周六) 晚上9:42
收件人: "lxk0301/scripts"<scripts@noreply.github.com&gt;;
抄送: "1021030435"<zhouzhengai@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [lxk0301/scripts] 关于执行结果问题 (#284)




 
看你用什么跑的
 如果github Action应该没啥问题
 
腾讯云函数 需要手动本地下载依赖后全量上传，在线依赖会有兼容问题
 
本地跑如果用 crontab触发必须注意环境变量
 crontab环境变量不是系统的环境变量，这个百度有解决方案
 0 0 * * * . /etc/profile; cd /scripts/  &amp;&amp; node jd_speed.js
