### ISSUE TITLE
surge使用JD_extra_cookie.js时报错

### ISSUE THREAD

**Issue by wd89124** [lxk0301/scripts#285]
大佬，我是surge用户，使用JD_extra_cookie.js这个的时候报下面的错误，是我的使用姿势有问题嘛，麻烦解答一下。谢谢！
![IMG_0250](https://user-images.githubusercontent.com/46956261/97780943-de2c9080-1bc2-11eb-8388-d419d2bb4914.PNG)

**Comment by lxk0301** [comment]
。。。这个只是用来获取cookie的 不是要你手动来执行的

**Comment by wd89124** [comment]
> 。。。这个只是用来获取cookie的 不是要你手动来执行的

大佬，按照这个办法获取cookie没反应，不知道是哪里出了问题

**Comment by lxk0301** [comment]
@wd89124 自己按脚本里面的说明添加号配置就行了。

还有目前脚本没有兼容这个获取cookie的。
