### ISSUE TITLE
jd_collectProduceScore未收取金币

### ISSUE THREAD

**Issue by zhuzf88** [lxk0301/scripts#286]
之前一直正常，今天下午开始出错。

==================脚本执行- 北京时间(UTC+8)：10/31/2020, 9:35:17 PM=====================

小功能::仅仅是收集一下京东双十一全名营业每秒产生的金币,建议一个小时跑一次脚本

🔔京东全民营业领金币, 开始!

🔔京东全民营业领金币, 结束! 🕛 1.737 秒

**Comment by Tersd07** [comment]
是的，总显示`活动太火爆了`。
另一个项目的脚本也是 https://github.com/zarkin404/sweater/tree/master/jingdong/2020_universal_operations
都是从今天开始的。

**Comment by mengdie101** [comment]
==================脚本执行- 北京时间(UTC+8)：11/2/2020, 3:34:16 PM=====================


小功能::仅仅是收集一下京东双十一全名营业每秒产生的金币,建议一个小时跑一次脚本

京东账号1成功收集金币失败:活动太火爆了
京东账号2成功收集金币失败:活动太火爆了

🔔京东全民营业领金币, 开始!

🔔京东全民营业领金币, 结束! 🕛 1.204 秒
