### ISSUE TITLE
github action手动触发验证代码可执行性建议

### ISSUE THREAD

**Issue by DoveBoy** [lxk0301/scripts#29]
有时更新项目pull request后，会出现merge失败，需要解决冲突。此时没有好办法解决，只能删除项目，重新fork。一切设置完成后，每次需要验证设置是否正确以及github action能否正常工作时总是特别麻烦，作者可否在workflows文件夹下的每个yml中加入“watch:types: started”一段代码，使其能够通过点击star来手动触发github action？

**Comment by lxk0301** [comment]
可行。不过具体怎么加呢？我没用过这个

**Comment by DoveBoy** [comment]
> 可行。不过具体怎么加呢？我没用过这个

已通过pull request发送了，测试手动star可以触发github action

**Comment by lxk0301** [comment]
已添加, 另外加了判断, 只有仓库私有人, 点star才有反应

**Comment by DoveBoy** [comment]
> 已添加, 另外加了判断, 只有仓库私有人, 点star才有反应

感谢！
