### ISSUE TITLE
农场、萌宠、种豆互助码

### ISSUE THREAD

**Issue by macheng716** [lxk0301/scripts#293]
东东农场：
88a661231c504d9db5fd53a04be3752d@5dc2fab7051f4969a459f8fa10ccff51
东东萌宠：
MTE1NDQ5OTIwMDAwMDAwMzUyMTM4OTk=@MTE1NDAxNzcwMDAwMDAwMzUyODA5MzE=
种豆得豆：
fb227jqogvovf5dekrautr3vly3h7wlwy7o5jii@wrirm5dzfnv263tamt5d3dc3fa5ac3f4ijdgqji

**Comment by lxk0301** [comment]
互助去这里

https://github.com/lxk0301/scripts/issues/66
