### ISSUE TITLE
盲盒脚本运行结束,但没起作用

### ISSUE THREAD

**Issue by GitCourser** [lxk0301/scripts#3]
运行环境是node.js

日志输出:

成功领取[object Object]热力值       <--------好像这里有问题,没有热力值
请继续等待,正在做任务,不要退出哦

🔔热8超级魔盒, 开始!

==============📣系统通知📣==============
热8超级魔盒
【京东账号一】
任务已做完.
 抽奖详情查看 https://blindbox.jd.com

🔔热8超级魔盒, 结束! 🕛 2.769 秒

**Comment by lxk0301** [comment]
这个问题是cookie失效了。你弄个新的ck？

**Comment by GitCourser** [comment]
不会失效啊,NobyDa大佬的签到脚本每天都正常运行,我直接使用同一个cookie

**Comment by GitCourser** [comment]
`var fs = require("fs");
var data = fs.readFileSync('cookie.txt');
const Key = data.toString();`
我的cookie是放文件里读取的,在你的脚本前加这段代码(只用了盲盒脚本,其他没用过),NobyDa签到脚本也是这样加的

**Comment by lxk0301** [comment]
@GitCourser  如果是pc上面node.js运行 ，应该不会出现 上面的问题， 但是在iPhone手机Loon这个软件， 确实会出现此问题。

我这边调试都是在PC上面使用node.js进行调试脚本的。

**Comment by GitCourser** [comment]
我用的不是pc,是在nas上,系统armbian
loon上能解决吗,说不定那边解决了,armbian这边也行了

**Comment by lxk0301** [comment]
> 我用的不是pc,是在nas上,系统armbian
> loon上能解决吗,说不定那边解决了,armbian这边也行了

我也不清楚是我脚本问题， 还是软件的问题， iOS上面surge和圈x都无此问题， 但是Loon出现此问题。
你那边去魔盒活动拿个ck去测试一下  
https://blindbox.jd.com

**Comment by GitCourser** [comment]
奇怪,居然成了,我之前的cookie没过期呀,但是重新提取cookie后又能用了......

**Comment by lxk0301** [comment]
> 奇怪,居然成了,我之前的cookie没过期呀,但是重新提取cookie后又能用了......

难道是 魔盒这边只能用从魔盒提取的ck吗？
但是我刚才在Loon上面测试过， 从魔盒这边拿的ck，也会提示未登陆， 很迷

**Comment by GitCourser** [comment]
不是,我又提取了其他京东页面的cookie,也能运行,这活动是12号开始的,我怀疑是12号之前的cookie不能用

**Comment by lxk0301** [comment]
> 不是,我又提取了其他京东页面的cookie,也能运行,这活动是12号开始的,我怀疑是12号之前的cookie不能用

可是我用Loon测试， 也是刚拿的新的ck,

**Comment by GitCourser** [comment]
那就可能是loon软件问题
