### ISSUE TITLE
星推官圈x出错

### ISSUE THREAD

**Issue by winxp0621** [lxk0301/scripts#302]
出错位置
  let cookiesData = $.getdata('CookiesJD') || "[]";
  cookiesData = JSON.parse(cookiesData);

貌似我的CookiesJD这个值不是个对象就是个cookie。JSON.parse的时候出的错

**Comment by lxk0301** [comment]
靠脚本自动获取的正常, 复制粘贴去修改的好像确实会出现这个问题

**Comment by winxp0621** [comment]
改为自动获取了
