### ISSUE TITLE
用actions手动触发不了啊

### ISSUE THREAD

**Issue by xiaokaig** [lxk0301/scripts#303]
刚开始star和修改文件 actions里都是空的， 后来执行了也只有sync-lxk0301-scripts这一个

**Comment by lxk0301** [comment]
被关闭了, 自己手动去一个一个开启

**Comment by xiaokaig** [comment]
> 被关闭了, 自己手动去一个一个开启

怎么开启😂不开启到时间会执行吗

**Comment by xiaokaig** [comment]
找到了   谢谢大佬
