### ISSUE TITLE
关于tg_user_id

### ISSUE THREAD

**Issue by fakegit** [lxk0301/scripts#306]
https://core.telegram.org/bots/api#sendmessage
看api文档，chat_id应该是跟机器人聊天的chat_id，频道的id，频道的username
英文原文：Unique identifier for the target chat or username of the target channel (in the format @channelusername)

并不是user_id，需要tg先跟bot聊天，通过getupdates获取到聊天的chat_id

**Comment by lxk0301** [comment]
😂😂是有什么指教的或者可以优化的吗？

**Comment by fakegit** [comment]
> 😂😂是有什么指教的或者可以优化的吗？

只是觉得tg_user_id这个说法不对，容易产生误解，很多人尤其是新手会以为是获取的user_id

另外我想问下，如果我设置了JD_DEBUG=false，还会推送到tg吗？

不设置JD_DEBUG=false的话会泄露京东用户ID，能提供个参数，星号敏感信息而又打印log
例如SECRET_LOG=True，username会输出为*****

**Comment by lxk0301** [comment]
@fakegit JD_DEBUG不管是什么。都能shou d推送通知。第二点不想弄。

**Comment by fakegit** [comment]
好吧

**Comment by lxk0301** [comment]
@fakegit 或者你想的话。弄好pr过来也行😀😀
