### ISSUE TITLE
文档有些地方描述不够清楚

### ISSUE THREAD

**Issue by DarkAge2018** [lxk0301/scripts#309]
1.docker-compose.yml环境变量值true和false是否需要加""
对不起，我看漏了，原来不需要
2.#crontab /scripts/docker/my_crontab_list.sh **#如果挂载了自定义任务文件 需要在 crond 的上面加行**
注释看起来让人困惑，改成取消注释即可

3.取关店铺secret的说明
如果我收藏了3个商品，不想被取关，在JD显示是这样子
APPLE
XIAOMI
HONOR
那么是不是要写成100&100&APPLE&***旗舰店

4.jd_scripts/my_crontab_list.sh 参考内容 和crontab_list.sh内容不一致，少了
**2 */1 * * * crontab /scripts/docker/${CRONTAB_LIST_FILE}**

5.签到领京豆可以改成两次，18点领的基本都是空的

**Comment by lxk0301** [comment]
`3.取关店铺secret的说明`
请认真看图说明
![image](https://user-images.githubusercontent.com/21308593/97961782-e1a45f80-1dee-11eb-889f-4caaa4d01f66.png)

`4.jd_scripts/my_crontab_list.sh 参考内容 和crontab_list.sh内容不一致`
他的作用是读取${CRONTAB_LIST_FILE} 这环境变量文件名 作为生效 crontab 任务 , my_crontab_list.sh可以不用添加,所以不存在遗漏


`5.签到领京豆可以改成两次，18点领的基本都是空的`  ., 不想你可以自定义cron

**Comment by DarkAge2018** [comment]
那个说明之前就看了，不太明白遇到多个商品怎么处理
UN_SUBSCRIBES 那里写**共四个参数,换行隔开**
我才理解成只能写一个商品和店铺名称，所以发出上面的疑问
名称是否需要全称，还是开头的几个关键字

**Comment by lxk0301** [comment]
都行
