### ISSUE TITLE
手动执行action中的workflow总是被skipped

### ISSUE THREAD

**Issue by Castle1984** [lxk0301/scripts#310]
Github上手动run workflow总是发现提示信息为This check was skipped
但是scheduled的启动方式能正常执行
这是什么原因？
我是在团队中fork的，在个人账户中手动run workflow没有任何问题。至于这么做的原因是我有两个账户，但是做星推官这个任务我希望两个账号并发执行，但是星推官的这脚本的自动启动时间延迟很高，所以想fork出两个项目
求教作者大大 @lxk0301 ，我也挺想弄懂的。

**Comment by lxk0301** [comment]
提示信息为This check was skipped 是因为yml文件添加了 

`if: github.event.repository.owner.id == github.event.sender.id`

目的是为了避免被其他人点击 Star 导致的不必要的麻烦

然后你的问题是说在什么团队fork,  可能就是因为你不是仓库所有者

![image](https://user-images.githubusercontent.com/21308593/97961515-6e025280-1dee-11eb-8f25-b073672b75db.png)

**Comment by Castle1984** [comment]
问题解决了，真的很感谢作者大大！
