### ISSUE TITLE
新手疑问：无法正常读取cookie

### ISSUE THREAD

**Issue by xizaha** [lxk0301/scripts#311]
1、{"name":"RequestError","code":"ERR_INVALID_CHAR"}
京豆签到 API请求失败，请检查网路重试
2、东东萌宠: API查询请求失败 ‼️‼️
{"name":"RequestError","code":"ERR_INVALID_CHAR"}

❗️东东萌宠, 错误!
RequestError: Invalid character in header content ["cookie"]
第一次接触不太明白怎么修改，请问需要怎么解决这个问题？

**Comment by lxk0301** [comment]
你的cookie不规范

**Comment by xizaha** [comment]
> 你的cookie不规范

两个cookie单独使用时运行正常。但是合并时，不论使用何种格式，均会报错。

**Comment by lxk0301** [comment]
你合并错了啊。用什么环境也不说一下。叫我猜？

**Comment by xizaha** [comment]
> 你合并错了啊。用什么环境也不说一下。叫我猜？

真的不好意思，我使用的是GitHub Action。在"秘密"项下，新建“JD_COOKIE”。在value框里填入两/三组cookie，使用回车键分行。一般只能运行第一个cookie。

![微信图片_20201106115006](https://user-images.githubusercontent.com/73636015/98324172-85c41b80-2026-11eb-9cae-3c6af97d8032.jpg)

**Comment by lxk0301** [comment]
![image](https://user-images.githubusercontent.com/21308593/98324784-2a932880-2028-11eb-872a-38df326bef14.png)

看了你的日志， 里面就是显示你只输入了一个账号，每次新增账号，都是要把之前的ck也放进去的，

**Comment by xizaha** [comment]
> ![image](https://user-images.githubusercontent.com/21308593/98324784-2a932880-2028-11eb-872a-38df326bef14.png)
> 
> 看了你的日志， 里面就是显示你只输入了一个账号，每次新增账号，都是要把之前的ck也放进去的，

发现原因了：第一组cookie之后要enter一下再粘贴下一组cookie。之前是粘贴玩所有cookie后再“；”后enter的。
