### ISSUE TITLE
星推官推送不显示用户名，能更新不··

### ISSUE THREAD

**Issue by leecheng310** [lxk0301/scripts#312]
RT

**Comment by leecheng310** [comment]
还有京豆变动也是··大佬为啥关闭··有啥禁忌么·

**Comment by lxk0301** [comment]
反馈问题是你这么反馈的么。就一句话  什么都没有

**Comment by leecheng310** [comment]
哦哦···失敬失敬··
农场这些server酱通知 
都是
设备通知
农场账号****

星推官和京豆变动
只有设备通知
星推官/京豆变动
能增加显示账号或昵称么

**Comment by lxk0301** [comment]
@leecheng310 截图

**Comment by leecheng310** [comment]
![Uploading image.png…]()

**Comment by leecheng310** [comment]
![Uploading 微信截图_20201103183526.png…]()

**Comment by leecheng310** [comment]
能看得到么

**Comment by lxk0301** [comment]
@leecheng310 你自己先看看有图片吗？弄成这样。还没上传成功救comment

**Comment by leecheng310** [comment]
哈哈··
![微信截图_20201103183526](https://user-images.githubusercontent.com/72600765/97975136-98aad600-1e03-11eb-9296-f34a26efe01a.png)

**Comment by leecheng310** [comment]
![微信截图_20201103183737](https://user-images.githubusercontent.com/72600765/97975186-afe9c380-1e03-11eb-8e7d-37a36e538eda.png)

**Comment by leecheng310** [comment]
京豆变动和星推官都是第一图的形式，看不到账号
