### ISSUE TITLE
关于“随机助力改成取20个码添加到固定助力的后面,”

### ISSUE THREAD

**Issue by hclasmn** [lxk0301/scripts#338]
能否提供是否加入的选项，老人家来了句：别人给我助力了，我得助力回去，结果现在一次助力都没了。，要被骂死

**Comment by hclasmn** [comment]
一个人只能助力4个，一个人助力满要5个，会不会出现某个人运行早把别人助力满了，自己甚至0

**Comment by lxk0301** [comment]
加在你固定队伍的后面,

又不影响你给找到的队友助力.

![image](https://user-images.githubusercontent.com/21308593/98355697-7ca27100-205d-11eb-9212-5929316aa7ea.png)

**Comment by lxk0301** [comment]
![image](https://user-images.githubusercontent.com/21308593/98355815-a5c30180-205d-11eb-918b-52fdcad97dc7.png)
