### ISSUE TITLE
workflow的问题

### ISSUE THREAD

**Issue by MW8023** [lxk0301/scripts#34]
大佬  可不可以将种豆得豆放进workflow里面呢

**Comment by lxk0301** [comment]
种豆目前没有支持多个账号,我这边暂不放里面, 你如果需要,你自行在你fork后的库里面(scripts\.github\workflows),添加下面这个文件就行(需解压) 
[jd_plantBean.zip](https://github.com/lxk0301/scripts/files/5193164/jd_plantBean.zip)

**Comment by MW8023** [comment]
好的  谢谢 大佬
