### ISSUE TITLE
星推官同一个账号的任务会做两遍

### ISSUE THREAD

**Issue by CNZedChou** [lxk0301/scripts#342]
任务23后，跳到了任务1
![image](https://user-images.githubusercontent.com/44132433/98391877-33b8df80-2092-11eb-8870-2da2fa7c9a25.png)

**Comment by lxk0301** [comment]
我知道。我的设计就是如此。跑第一遍是做任务。第二遍是领取

**Comment by CNZedChou** [comment]
好的，明白

**Comment by hacken156026692** [comment]
咨询一下，这个运行中，多策略已开启的界面，是什么APP？能够自己运行这星推官吗？谢谢
