### ISSUE TITLE
请问 下 京东多合一签到脚本是否可以添加下面4个网址？

### ISSUE THREAD

**Issue by dyingsu** [lxk0301/scripts#343]
那个，请问下京东多合一签到脚本是否可以添加下面4个来源？
1.金融 app 打开网址就可以领每天3京豆  https://uf1.jr.jd.com/up/redEnvelopes/index.html?actCode=30C4F86264&showhead=no&sid=e0693d73b1d5cbeaa544cf1490480c0w
2.金融 app打开网址就有每天1京豆 https://uf1.jr.jd.com/up/redEnvelopes/index.html?actCode=1D06AA3B0F

3.金融 app打开网址还需手动点击顶部 签到，一天 1京豆，满 7天 3 京豆 https://jdda.jd.com/app/hd/?sid=08a9bde8a80b8caaeebfedd9159cbe4w&#/gachakon?token=0d79b1b8139e416aac3ba96c0a018c93&from=qdynd

还有 第四个 是
4.金融 app 打开 网址 每天 领取 0.05 金贴
https://uf.jr.jd.com/up/redEnvelopes/index.html?actCode=F1455B50EF

**Comment by lxk0301** [comment]
此问题建议来这里提哦

https://github.com/NobyDa/Script/issues
