### ISSUE TITLE
关于GitHub Action的cron国际时间问题

### ISSUE THREAD

**Issue by charleyyy** [lxk0301/scripts#349]
看到教程里提到的Action里面cron时间是国际时间标准，我是直接fork的，不需要改每个脚本里的自动触发时间吧？是否还会在脚本设定的时间运行呢？
比如脚本中多合一签到是北京时间0:26，会不会在GitHub Action是北京时间8:26再运行呢

**Comment by lxk0301** [comment]
@charleyyy 时间已设置好。一般无需修改

**Comment by charleyyy** [comment]
> @charleyyy 时间已设置好。一般无需修改

感谢，现在看来掐点签到的需要自己手机运行，其他的挂着就行了，感谢！

**Comment by lxk0301** [comment]
@charleyyy 差不多就是这么个意思
