### ISSUE TITLE
能不能把项目名称改成中文啊？

### ISSUE THREAD

**Issue by xrzs168** [lxk0301/scripts#359]
能不能把项目名称改成中文啊？这样方便小白

**Comment by lxk0301** [comment]
不能

**Comment by lxk0301** [comment]
@lxk0301

**Comment by lxk0301** [comment]
这里很明白了。还不行建议放弃。别太为难自己

![6C453FDC-B50F-4D7F-9615-B68346E2553F](https://user-images.githubusercontent.com/21308593/98457879-fc4b4f80-21c5-11eb-92bb-55e0f35cdae9.png)

**Comment by xrzs168** [comment]
0.0
