### ISSUE TITLE
我的摇钱树项目是空的

### ISSUE THREAD

**Issue by xrzs168** [lxk0301/scripts#360]
显示“：没有结果与您的搜索匹配。
尝试扩大搜索过滤器。
请问大佬怎么解决啊

**Comment by lxk0301** [comment]
@xrzs168 你的描述。还不如来一张大的截图更加明了清晰

**Comment by xrzs168** [comment]
![RLEI7F488EA@U~ON572C7A](https://user-images.githubusercontent.com/73456261/98458217-3d912e80-21c9-11eb-9189-5e0bb3061cdc.png)

**Comment by xrzs168** [comment]
现在号了
