### ISSUE TITLE
Telegram Proxy

### ISSUE THREAD

**Issue by LuomingXu** [lxk0301/scripts#375]
由于电报不使用代理无法发送消息, 所以是否为TG消息发送添加**单独**的代理配置
在服务器上使用clash的代理测试, 是可行的(使用的是[docker](https://github.com/lxk0301/scripts/tree/master/docker)方法部署)

![image](https://user-images.githubusercontent.com/24503603/98492751-c2388700-2273-11eb-8e66-0dc6089d2030.png)
![image](https://user-images.githubusercontent.com/24503603/98492765-d086a300-2273-11eb-9982-85f0916481de.png)

在clash的log中可以看到成功走了代理
![image](https://user-images.githubusercontent.com/24503603/98492949-4985fa80-2274-11eb-9a56-a86b6f07bce9.png)

测试代码(获取自[sendNotify.js](https://github.com/lxk0301/scripts/blob/master/sendNotify.js)Line156)
需要[tunnel](https://github.com/koichik/node-tunnel)
```js
const $ = new Env();
// 代理依赖
const tunnel = require('tunnel');

function tgBotNotify(text, desp) {
  return new Promise(resolve => {
    if (TG_BOT_TOKEN && TG_USER_ID) {
      const options = {
        url: `https://api.telegram.org/bot${TG_BOT_TOKEN}/sendMessage`,
        body: `chat_id=${TG_USER_ID}&text=${text}\n\n${desp}&disable_web_page_preview=true`,
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded'
        },
        agent: {
          https: tunnel.httpsOverHttp({
            proxy: {
              host: '192.168.168.51', // 使用环境变量配置
              port: 1080 // 使用环境变量配置
            }
          })
        }
      }
...

tgBotNotify('text', 'desp')
```

由于本人不怎么会js, node所以未PR :)

**Comment by lxk0301** [comment]
添加这个后, 那一些能直连外网的怎么办?  
```
agent: {
          https: tunnel.httpsOverHttp({
            proxy: {
              host: '192.168.168.51', // 使用环境变量配置
              port: 1080 // 使用环境变量配置
            }
          })
        }
```

**Comment by LuomingXu** [comment]
所以感觉可以写两个函数? 一个有这个配置, 一个没有? (根据是否在环境变量中配置了代理)
就需要对代码修改一下

**Comment by lxk0301** [comment]
![image](https://user-images.githubusercontent.com/21308593/98495162-87395200-2279-11eb-8483-3fee8e1586dd.png)

这种方法有试过吗?

**Comment by LuomingXu** [comment]
我如此操作的
服务器上的代理使用的就是一个clash的容器
![image](https://user-images.githubusercontent.com/24503603/98495528-4988f900-227a-11eb-90fa-36d4f4c46789.png)

然后将clash和jd_scripts的容器加入同一个网路
![image](https://user-images.githubusercontent.com/24503603/98495413-07f84e00-227a-11eb-974f-ab992fa61731.png)
所以在上面的代码

```js
agent: {
          https: tunnel.httpsOverHttp({
            proxy: {
              host: '192.168.168.51', // 此处用的就是clash的ip地址
              port: 1132 // clash的代理地址
            }
          })
        }
```
然后就可以了

至于
![image](https://user-images.githubusercontent.com/24503603/98495732-d2a03000-227a-11eb-88d0-6a8e870abd7c.png)
未曾用过, 只用过docker pull使用代理[docker服务使用代理](https://docs.docker.com/network/proxy/), 容器指定代理...未用过

P.S. 我就是想**单独只有**电报的消息走代理, 所以才会提这个issue

**Comment by lxk0301** [comment]
已弄 ,环境变量为 `TG_PROXY_HOST`和`TG_PROXY_PORT`

**Comment by LuomingXu** [comment]
okay
README啥的, 就请你完善一下了

**Comment by lxk0301** [comment]
我重新改了一下, 你更新测试一下看看

**Comment by lxk0301** [comment]
你开头说的clash代理。是指的在服务器端搭建的吧？还是指pc上面的clash？

**Comment by LuomingXu** [comment]
可以

![image](https://user-images.githubusercontent.com/24503603/98530761-50cff700-22ba-11eb-80e7-d6e28517c9ca.png)

但是不知道为啥这边是null, 应该没啥关系, 下面是参数
```js
tgBotNotify("text", "desp")
```
话说, 这种方式更好?
```js
Object.assign(options, { agent })
```

> 你开头说的clash代理。是指的在服务器端搭建的吧？还是指pc上面的clash？

服务器上搭建的. 与jd_scripts在一个docker网络里面
当然如果你在本机上那也是可以的, 反正都是通过http协议, 自己配置就好了

**Comment by lxk0301** [comment]
为了兼容微信端的server酱通知。我做了一个正则兼容处理

**Comment by lxk0301** [comment]
Object.assign(options, { agent })  代码简洁些吧。

本地也能行的话，我明天本机试试看，我的dokcer正好不能tg推送。

**Comment by LuomingXu** [comment]
你是clash在host上, jd_scripts在docker里面?

**Comment by lxk0301** [comment]
@LuomingXu clash是指本地pc上clash for windows。jd_scripts在docker。

哈哈。估计不行。你刚才应该是误解我意思了

**Comment by LuomingXu** [comment]
可以的, 
不管你是docker for win(没测试, 应该是可以的)还是虚拟机(Linux)的docker, ip能够ping到就行
比如: 
这个是我的虚拟机里面的docker

![image](https://user-images.githubusercontent.com/24503603/98533440-f2a51300-22bd-11eb-9bd4-1f5560e8e08a.png)

我现在进入容器里面, ping我的host

![image](https://user-images.githubusercontent.com/24503603/98533515-0badc400-22be-11eb-8e64-44902ac30389.png)

关键就是这个ip, 我在此的ip就是我host在路由器中的ip
若是你ping不到的话, 可以在dns里面配置你的路由器ip, 一般就可以ping到你的host了

![image](https://user-images.githubusercontent.com/24503603/98533717-47e12480-22be-11eb-9e76-70e1e4bea6b6.png)

**Comment by lxk0301** [comment]
我明天试试看。 此外我是虚拟机的docker
