### ISSUE TITLE
京东取关脚本运行失败

### ISSUE THREAD

**Issue by Naughty-Monkey** [lxk0301/scripts#39]
当关注店铺为0，关注商品不为0时。脚本运行直接结束，无法进行取消关注商品操作

**Comment by lxk0301** [comment]
这个为0 ， 是什么意思？ 已关注的店铺/商品数量吗？

**Comment by DoveBoy** [comment]
> 当关注店铺为0，关注商品不为0时。脚本运行直接结束，无法进行取消关注商品操作

jd_unsubscribe.js 脚本，自己改下34和35行代码就可以了，0代表不取关，其他数字代表每次运行取关的数量

**Comment by lxk0301** [comment]
> > 当关注店铺为0，关注商品不为0时。脚本运行直接结束，无法进行取消关注商品操作
> 
> jd_unsubscribe.js 脚本，自己改下34和35行代码就可以了，0代表不取关，其他数字代表每次运行取关的数量

我怎么感觉他说的数字0， 不是这个设置为0的问题， 而是店铺数量的问题。

**Comment by DoveBoy** [comment]
> > > 当关注店铺为0，关注商品不为0时。脚本运行直接结束，无法进行取消关注商品操作
> > 
> > 
> > jd_unsubscribe.js 脚本，自己改下34和35行代码就可以了，0代表不取关，其他数字代表每次运行取关的数量
> 
> 我怎么感觉他说的数字0， 不是这个设置为0的问题， 而是店铺数量的问题。

本身他表述的就不是太清楚，我也不太明白到底指什么😂

**Comment by Naughty-Monkey** [comment]
我说的是店铺数量是0，商品数不为0，我在boxjs里面把默认的10改成20以后，就可以了
