### ISSUE TITLE
脚本Cookie问题以及jd_unsubscribe.js的疑问

### ISSUE THREAD

**Issue by DoveBoy** [lxk0301/scripts#4]
@lxk0301 能不能增加一个单独的cookie文件，所有脚本自动调取cookie？而不用每个脚本去单独设置cookie？这样太麻烦了

**Comment by DoveBoy** [comment]
@lxk0301 另外还有一个问题请求开发者解答，京东取关商品和店铺的脚本[jd_unsubscribe.js](https://github.com/lxk0301/scripts/blob/master/jd_unsubscribe.js)，运行在nodejs环境下，通过修改哪一行代码可以实现只取关店铺而不取关商品？自己根据代码注释尝试将**const goodPageSize = $.getdata('jdUnsubscribePageSize') || 10;// 运行一次取消多少个已关注的商品。**中的10改成0，依旧会取关商品

**Comment by lxk0301** [comment]
> @lxk0301 另外还有一个问题请求开发者解答，京东取关商品和店铺的脚本[jd_unsubscribe.js](https://github.com/lxk0301/scripts/blob/master/jd_unsubscribe.js)，运行在nodejs环境下，通过修改哪一行代码可以实现只取关店铺而不取关商品？自己根据代码注释尝试将**const goodPageSize = $.getdata('jdUnsubscribePageSize') || 10;// 运行一次取消多少个已关注的商品。**中的10改成0，依旧会取关商品

是这个零哦。'0'

**Comment by lxk0301** [comment]
> @lxk0301 能不能增加一个单独的cookie文件，所有脚本自动调取cookie？而不用每个脚本去单独设置cookie？这样太麻烦了

这个问题下午看看

**Comment by GitCourser** [comment]
单独的cookie文件,我自己改的,把cookie放到cookie.txt里
`var fs = require("fs");
var data = fs.readFileSync('cookie.txt');
var Key = data.toString();`

**Comment by DoveBoy** [comment]
> > @lxk0301 另外还有一个问题请求开发者解答，京东取关商品和店铺的脚本[jd_unsubscribe.js](https://github.com/lxk0301/scripts/blob/master/jd_unsubscribe.js)，运行在nodejs环境下，通过修改哪一行代码可以实现只取关店铺而不取关商品？自己根据代码注释尝试将**const goodPageSize = $.getdata('jdUnsubscribePageSize') || 10;// 运行一次取消多少个已关注的商品。**中的10改成0，依旧会取关商品
> 
> 是这个零哦。'0'

好吧，现在可以了，建议说明文档中写明，因为没有iPhone，所以没法用Quantumult X, Surge, Loon, JSBox，只能用Nodejs跑JS，只能修改原脚本

**Comment by DoveBoy** [comment]
> > @lxk0301 能不能增加一个单独的cookie文件，所有脚本自动调取cookie？而不用每个脚本去单独设置cookie？这样太麻烦了
> 
> 这个问题下午看看

种豆得豆能否考虑增加帮好友收取营养液的功能？当好友营养液大于一定数量才收取，这个值可以通过修改原脚本代码自定义。宠汪汪怎么修改，可以只偷取好友的狗粮以及金币，而不帮喂？

**Comment by lxk0301** [comment]
> require

这个也行

**Comment by lxk0301** [comment]
> > > @lxk0301 另外还有一个问题请求开发者解答，京东取关商品和店铺的脚本[jd_unsubscribe.js](https://github.com/lxk0301/scripts/blob/master/jd_unsubscribe.js)，运行在nodejs环境下，通过修改哪一行代码可以实现只取关店铺而不取关商品？自己根据代码注释尝试将**const goodPageSize = $.getdata('jdUnsubscribePageSize') || 10;// 运行一次取消多少个已关注的商品。**中的10改成0，依旧会取关商品
> > 
> > 
> > 是这个零哦。'0'
> 
> 好吧，现在可以了，建议说明文档中写明，因为没有iPhone，所以没法用Quantumult X, Surge, Loon, JSBox，只能用Nodejs跑JS，只能修改原脚本

忘记说明啦 ，其实数字0也比较好理解一点， 我这边已做修复，填写数字0即可。

**Comment by lxk0301** [comment]
> 种豆得豆能否考虑增加帮好友收取营养液的功能

1、种豆得豆帮好友收取营养液的功能已有。只有3瓶的时候，帮好友收取才会奖励自己一瓶

2、宠汪汪帮好友喂食每天能拿积分，上限是200积分。也就是喂食20个好友，如果不想喂食，请注释掉此段代码,
目前在第162行，搜索关键字helpFeed
```
                if (getFriendsResult.datas[i]["status"] == "not_feed") {
                  let helpFeedResult = yield helpFeed(friendPin)
                  console.log(`帮忙喂食结果${JSON.stringify(helpFeedResult)}`)
                }
```

**Comment by DoveBoy** [comment]
> > > > @lxk0301 另外还有一个问题请求开发者解答，京东取关商品和店铺的脚本[jd_unsubscribe.js](https://github.com/lxk0301/scripts/blob/master/jd_unsubscribe.js)，运行在nodejs环境下，通过修改哪一行代码可以实现只取关店铺而不取关商品？自己根据代码注释尝试将**const goodPageSize = $.getdata('jdUnsubscribePageSize') || 10;// 运行一次取消多少个已关注的商品。**中的10改成0，依旧会取关商品
> > > 
> > > 
> > > 是这个零哦。'0'
> > 
> > 
> > 好吧，现在可以了，建议说明文档中写明，因为没有iPhone，所以没法用Quantumult X, Surge, Loon, JSBox，只能用Nodejs跑JS，只能修改原脚本
> 
> 忘记说明啦 ，其实数字0也比较好理解一点， 我这边已做修复，填写数字0即可。

那现在是填'0'还是直接填0就可以？

**Comment by lxk0301** [comment]
@DoveBoy  数字0

**Comment by DoveBoy** [comment]
> @DoveBoy 数字0

谢谢，现在直接填0，用nodejs跑不会报错了

**Comment by lxk0301** [comment]
> > @DoveBoy 数字0
> 
> 谢谢，现在直接填0，用nodejs跑不会报错了

你nodejs用的是云服务器吗？

**Comment by DoveBoy** [comment]
> > > @DoveBoy 数字0
> > 
> > 谢谢，现在直接填0，用nodejs跑不会报错了
> 
> 你nodejs用的是云服务器吗？

不是，我在安卓上安装termux，nodejs是跑在本地的

**Comment by lxk0301** [comment]
@DoveBoy  termux？那这个不会定时运行脚本。只能手动哇

**Comment by DoveBoy** [comment]
> @DoveBoy  termux？那这个不会定时运行脚本。只能手动哇

是的呢，我想把大佬的脚本用github action跑，但是看workflow，似乎还会跑jd_unsubscribe，可是我不需要跑这个。能不能把日常任务的脚本放入workflow

**Comment by lxk0301** [comment]
> > @DoveBoy  termux？那这个不会定时运行脚本。只能手动哇
> 
> 是的呢，我想把大佬的脚本用github action跑，但是看workflow，似乎还会跑jd_unsubscribe，可是我不需要跑这个。能不能把日常任务的脚本放入workflow

github action我还在测试玩，至于你说的会跑取关脚本，那是在于你的配置 ，你在workflow里面没有加取关脚本。 就行了。

**Comment by DoveBoy** [comment]
> > > @DoveBoy  termux？那这个不会定时运行脚本。只能手动哇
> > 
> > 是的呢，我想把大佬的脚本用github action跑，但是看workflow，似乎还会跑jd_unsubscribe，可是我不需要跑这个。能不能把日常任务的脚本放入workflow
> 
> github action我还在测试玩，至于你说的会跑取关脚本，那是在于你的配置 ，你在workflow里面没有加取关脚本。 就行了。

现在workflows文件夹下只有一个node.js.yml，我是直接把需要跑的脚本放到workflows文件夹下就可以了吗？

**Comment by lxk0301** [comment]
@DoveBoy 不是。 那是我的测试文件。 正式的下午写

**Comment by DoveBoy** [comment]
> @DoveBoy 不是。 那是我的测试文件。 正式的下午写

期待开发者加入这个功能，解放双手了👍

**Comment by lxk0301** [comment]
> > @DoveBoy 不是。 那是我的测试文件。 正式的下午写
> 
> 期待开发者加入这个功能，解放双手了👍

嗯。正在和@Zero-S1大佬学习github action。我也是刚听说。

**Comment by DoveBoy** [comment]
> > > @DoveBoy 不是。 那是我的测试文件。 正式的下午写
> > 
> > 
> > 期待开发者加入这个功能，解放双手了👍
> 
> 嗯。正在和[@Zero-S1](https://github.com/Zero-S1/JD_tools)大佬学习github action。我也是刚听说。

已经看到开发者在测试workflows了，感谢开发者！希望能将东东农场，天天加速，宠汪汪，东东萌宠，种豆得豆，摇钱树都加入到workflows自动定时任务，手动nodejs太麻烦了，大佬的脚本越来越好用了。开发者有空能完善下京喜工厂吗？我看目前这个脚本刚起步

**Comment by lxk0301** [comment]
> > > > @DoveBoy 不是。 那是我的测试文件。 正式的下午写
> > > 
> > > 
> > > 期待开发者加入这个功能，解放双手了👍
> > 
> > 
> > 嗯。正在和[@Zero-S1](https://github.com/Zero-S1/JD_tools)大佬学习github action。我也是刚听说。
> 
> 已经看到开发者在测试workflows了，感谢开发者！希望能将东东农场，天天加速，宠汪汪，东东萌宠，种豆得豆，摇钱树都加入到workflows自动定时任务，手动nodejs太麻烦了，大佬的脚本越来越好用了。开发者有空能完善下京喜工厂吗？我看目前这个脚本刚起步

已经有部分脚本在workflows里面了。惊喜工厂是定时任务，单靠脚本完成不了 要拉人头

**Comment by DoveBoy** [comment]
> > > > > @DoveBoy 不是。 那是我的测试文件。 正式的下午写
> > > > 
> > > > 
> > > > 期待开发者加入这个功能，解放双手了👍
> > > 
> > > 
> > > 嗯。正在和[@Zero-S1](https://github.com/Zero-S1/JD_tools)大佬学习github action。我也是刚听说。
> > 
> > 已经看到开发者在测试workflows了，感谢开发者！希望能将东东农场，天天加速，宠汪汪，东东萌宠，种豆得豆，摇钱树都加入到workflows自动定时任务，手动nodejs太麻烦了，大佬的脚本越来越好用了。开发者有空能完善下京喜工厂吗？我看目前这个脚本刚起步
> 
> 已经有部分脚本在workflows里面了。惊喜工厂是定时任务，单靠脚本完成不了 要拉人头

已经fork并开启了github action目前3个用着正常

**Comment by lxk0301** [comment]
@DoveBoy 我还没写action的具体使用教程你就会用啦？

**Comment by lxk0301** [comment]
@DoveBoy 多账号的ck是用&隔开。不是换行

**Comment by DoveBoy** [comment]
> @DoveBoy 我还没写action的具体使用教程你就会用啦？

啊？之前用过类似的GitHub action设置，看过yml源代码，知道大概怎么设置，我只用单账号，fork项目后，setting中，secret新建JD_COOKIE，值填上抓取的cookie就行（目前测试只需要填上pt_key=xxx;pt_pin=xxx;这一段就行，手机号码+验证码的形式能有一个月有效期，其余都只有几天。控制台document.cookie方式抓取的cookie不全，原因未知，Google很久未果，大佬知道原因吗？）我就是这么设置的，目前云端跑没收到报错邮件，有什么不对的地方请开发者指导一下

**Comment by lxk0301** [comment]
> > @DoveBoy 我还没写action的具体使用教程你就会用啦？
> 
> 啊？之前用过类似的GitHub action设置，看过yml源代码，知道大概怎么设置，我只用单账号，fork项目后，setting中，secret新建JD_COOKIE，值填上抓取的cookie就行（目前测试只需要填上pt_key=xxx;pt_pin=xxx;这一段就行，手机号码+验证码的形式能有一个月有效期，其余都只有几天。控制台document.cookie方式抓取的cookie不全，原因未知，Google很久未果，大佬知道原因吗？）我就是这么设置的，目前云端跑没收到报错邮件，有什么不对的地方请开发者指导一下

pc获取ck。 可以看我readme里面的 

3、获取京东cookie教程可参考 浏览器获取京东cookie教程

**Comment by DoveBoy** [comment]
> > > @DoveBoy 我还没写action的具体使用教程你就会用啦？
> > 
> > 
> > 啊？之前用过类似的GitHub action设置，看过yml源代码，知道大概怎么设置，我只用单账号，fork项目后，setting中，secret新建JD_COOKIE，值填上抓取的cookie就行（目前测试只需要填上pt_key=xxx;pt_pin=xxx;这一段就行，手机号码+验证码的形式能有一个月有效期，其余都只有几天。控制台document.cookie方式抓取的cookie不全，原因未知，Google很久未果，大佬知道原因吗？）我就是这么设置的，目前云端跑没收到报错邮件，有什么不对的地方请开发者指导一下
> 
> pc获取ck。 可以看我readme里面的
> 
> 3、获取京东cookie教程可参考 浏览器获取京东cookie教程

浏览器获取cookie的方法我知道，直接控制台，network-过滤doc，查找head文件，里面有cookie完整信息。只是奇怪两种方法获取的cookie不一样，document.cookie获取的少一段。另外最简单的获取cookie方法是Google浏览器安装edit cookie插件，一键导出cookie到剪贴板

**Comment by lxk0301** [comment]
@DoveBoy 
![image](https://user-images.githubusercontent.com/21308593/90583169-18140a80-e202-11ea-8e81-45dfd4f02f8a.png)

**Comment by DoveBoy** [comment]
> @DoveBoy
> ![image](https://user-images.githubusercontent.com/21308593/90583169-18140a80-e202-11ea-8e81-45dfd4f02f8a.png)

地点和我现在所在地不同，听说京东后台会看这个，不在常用收货地址会黑号，一直没敢用云函数
![image](https://user-images.githubusercontent.com/19201447/90594740-b5306c80-e21d-11ea-91c7-d1aaff89d105.png)

**Comment by lxk0301** [comment]
@DoveBoy  你用github action  ，里面的ip都是国外的，

**Comment by DoveBoy** [comment]
> @DoveBoy 你用github action ，里面的ip都是国外的，

云函数怎么用？貌似不能上传文件，只能复制代码过去，感觉设置不如github action好用

**Comment by lxk0301** [comment]
> > @DoveBoy 你用github action ，里面的ip都是国外的，
> 
> 云函数怎么用？貌似不能上传文件，只能复制代码过去，感觉设置不如github action好用

用腾讯云函数 ,需要先在本地npm install安装依赖包后, 然后在云函数选择上传本地文件,才能用.
