### ISSUE TITLE
京东农场surge手工执行只能看到第一个帐号的信息

### ISSUE THREAD

**Issue by askiter** [lxk0301/scripts#44]
我已经成功拿到两个帐号的cookie了，手工执行的时候只能看到第一个帐号的信息，提示了我的sharecode，第二个帐号的执行日志无法看到，也看不到第二个帐号的sharecode。

我在jsbox里面填写了第二个帐号的账号名，同时把上面的sharecode填到了第二个账户的助力sharecode列表中，结果依然是看不到第二个帐号的执行信息。

手工执行的时候，提示不能给自己助力，可我明明是把第一个帐号的sharecode填值到了第二个帐号的助力sharecode里面了啊。
请问这个情况怎么解决，包括如何获得第二个帐号的sharecode，谢谢

**Comment by lxk0301** [comment]
没有日志，没有截图。没太明白，进tg群组发图说下吧

https://t.me/JD_fruit_pet
