### ISSUE TITLE
大佬你好，请教一下脚本中的参数问题

### ISSUE THREAD

**Issue by s7964926** [lxk0301/scripts#45]
大佬你好，想请问一下wake-system=1是什么含义呢

**Comment by lxk0301** [comment]
这是iOS surge软件的cron相关的设置，和脚本无关

**Comment by s7964926** [comment]
其实想问一下，就是这句是什么意思…

**Comment by lxk0301** [comment]
我没有surge，猜测一下的意思就 是 是否唤醒系统。1表示是
![544DC9E9-8A23-4C0F-A3D7-25DAD57AEF89](https://user-images.githubusercontent.com/21308593/93714710-2c4b7e80-fb97-11ea-95c9-b8f4accc371a.jpeg)
