### ISSUE TITLE
大佬 整个京喜农场 京喜工厂 京喜财福岛 京喜瓜分红包呗

### ISSUE THREAD

**Issue by Zhuzhen6** [lxk0301/scripts#5]
大佬 整个京喜农场 京喜工厂 京喜财福岛 京喜瓜分红包呗

**Comment by lxk0301** [comment]
@Zhuzhen6 惊喜好像都是限时任务吧?还有很多拉人头的?

**Comment by Zhuzhen6** [comment]
京喜农场都是有做任务的 跟东东农场一样 浏览任务

**Comment by lxk0301** [comment]
> 京喜农场都是有做任务的 跟东东农场一样 浏览任务

惊喜农场我看过。是有时间限制的。到了时间完成目标。就要重新开始
