### ISSUE TITLE
助力、邀请的问题

### ISSUE THREAD

**Issue by Wake326** [lxk0301/scripts#50]
本人小白，想请问下大佬，能否实现多账号登陆的，自动相互邀请各个账号？如若不行，脚本运行过程中出现的助力码，又该填写到何处让账号之间相互邀请？

**Comment by lxk0301** [comment]
你要哪种使用方式

**Comment by Wake326** [comment]
谢谢大佬回复，gihub的动作方式。

**Comment by lxk0301** [comment]
> 谢谢大佬回复，gihub的动作方式。

宠汪汪的赛跑助力与邀请助力，github不可用。因为token要从手机端微信小程序获取，而且此token时效太短了， 只有几个小时。
这边是推荐iOS系统的代理软件使用

**Comment by Wake326** [comment]
嗯嗯，好的，明白了，谢谢大佬。
