### ISSUE TITLE
可以考虑实现每日关注店铺领京豆吗？

### ISSUE THREAD

**Issue by conanca** [lxk0301/scripts#52]
1. 这个接口可以拿到每日发布页的链接：
https://haojia.m.smzdm.com/daily_collection/carefully_chosen

2. 然后爬响应内容中这个链接
data.hot_widget.[0].link
得到每个领京豆的链接

3. 其中是关注店铺的，可以关注；其他活动可以不用管

**Comment by lxk0301** [comment]
活动入口说下？

**Comment by DoveBoy** [comment]
我也想这个，每天手动点太累了

**Comment by lxk0301** [comment]
你们两个说了这么多。也不见给个活动入口路径

**Comment by conanca** [comment]
活动入口页：
https://haojia.m.smzdm.com/daily_collection/every_day

**Comment by lxk0301** [comment]
这是什么值得购买收集的京东店铺链接。

**Comment by conanca** [comment]
> 这是什么值得购买收集的京东店铺链接。

对，这种只有找第三方的，没发现有官方活动路径

**Comment by lxk0301** [comment]
不考虑。感觉没有规律可循
