### ISSUE TITLE
京东农场本地运行错误

### ISSUE THREAD

**Issue by yellowOld** [lxk0301/scripts#53]
京东农场本地运行的装好依赖之后在jdCookie.js文件中替换cookie之后运行报错，获取不到farmUserPro属性。其他文件并未改动，报错如下图：

![image](https://user-images.githubusercontent.com/42842744/94258246-253dbb00-ff5f-11ea-873a-88ad529c2ffd.png)

**Comment by lxk0301** [comment]
你在1049行前面加上下面的打印看看吧。感觉你的数据不对

`console.log(data);`

**Comment by yellowOld** [comment]
这个我之前也看过了，没获取到数据，然后就走了catch跟finaly。

![image](https://user-images.githubusercontent.com/42842744/94265601-6b008080-ff6b-11ea-9430-419d695eb206.png)

**Comment by lxk0301** [comment]
你试试其他脚本运行看看。

还有你不会依赖包没按照吧😂

**Comment by yellowOld** [comment]
肯定装了呀！不会直接就报依赖的错了

**Comment by yellowOld** [comment]
肯定装了呀！没装直接就报依赖的错了。
装了这四个：crypto-js   http-server    tough-cookie    got
其他的脚本也试了。全报的这个错

**Comment by lxk0301** [comment]
我pc上面调试是正确的。你可试试第三种方法 使用github action试试吧

**Comment by yellowOld** [comment]
github action是可以的。我再看看问题到底出在哪吧！谢啦

**Comment by lxk0301** [comment]
证明不是你的ck有问题。而是你本机有问题了。你自行检查检查吧。网络或者依赖包什么
