### ISSUE TITLE
新的京东活动

### ISSUE THREAD

**Issue by LiJinChang** [lxk0301/scripts#55]
京东 app 底栏 → 发现  → 看一看，浏览 15 篇精选内容得 30 豆

**Comment by lxk0301** [comment]
没有找到哎， 可以截图看看么

**Comment by LiJinChang** [comment]
> 没有找到哎， 可以截图看看么

可能 Android 版才有
![Screenshot_20200928-140119_](https://user-images.githubusercontent.com/1154661/94395971-6e765080-0193-11eb-89aa-a48c35e21887.png)

**Comment by lxk0301** [comment]
已看到

**Comment by lxk0301** [comment]
抓包看了下。做不了。

**Comment by 36964117** [comment]
可惜了

**Comment by landcruser** [comment]
大佬，值得买有一些关注有礼的，每天有百十个，可否加入。
