### ISSUE TITLE
qx运行宠汪汪兑换脚本出错

### ISSUE THREAD

**Issue by MisterGlasses** [lxk0301/scripts#57]
2020/09/28 00:00:16:813  <console>    [JS Console]: 当前积分 6810
2020/09/28 00:00:16:813  <console>    [JS Console]: 宠物等级 11
2020/09/28 00:00:16:814  <console>    [JS Console]: 京东昵称 jd_7b22bbfe1e7e5
2020/09/28 00:00:16:814  <console>    [JS Console]: 当前京豆库存:4682
2020/09/28 00:00:16:815  <console>    [JS Console]: 当前账户积分:6810
当前京豆库存:4682
满足兑换条件,开始为您兑换京豆
2020/09/28 00:00:26:891  <console>    [JS Console]: 
❗️宠汪汪积分兑换奖品, 错误!
SyntaxError: JSON Parse error: Unexpected identifier "undefined"
2020/09/28 00:00:26:893  <console>    [JS Console]: 
❌ 宠汪汪积分兑换奖品, 失败! 原因: TypeError: undefined is not an object (evaluating 'exchangeRes.success')!
2020/09/28 00:00:26:894  <console>    [JS Console]: 
🔔宠汪汪积分兑换奖品, 结束! 🕛 21.49 秒
2020/09/28 00:00:26:895  <console>    [JS Console]: 
2020/09/28 00:00:30:375  <console>    [QTXTaskManager]

**Comment by lxk0301** [comment]
这个问题， 你只能重新运行一次脚本， 或者检查自身的情况(网络，mitm，广告拦截等等)

**Comment by MisterGlasses** [comment]
> 这个问题， 你只能重新运行一次脚本， 或者检查自身的情况(网络，mitm，广告拦截等等)

实际兑换成功 好像就这一次失败了

**Comment by lxk0301** [comment]
> > 这个问题， 你只能重新运行一次脚本， 或者检查自身的情况(网络，mitm，广告拦截等等)
> 
> 实际兑换成功 好像就这一次失败了

嗯 ，这个脚本出错的几率比较小。我目前还没出现过这个问题
