### ISSUE TITLE
京东农场助力的问题

### ISSUE THREAD

**Issue by MW8023** [lxk0301/scripts#6]
大佬，你好！
       你在京东农场的脚本里注释中写明了是每天助力好友上限是四个人，并且在box.js里面设置了四个互助码的输入框，可是代码里你判断了是大于等于5，所以我到现在都没有领取到额外的奖励，，嘻嘻嘻嘻 。。。希望大佬尽快处理更新上传，同时也感谢大佬一直付出与贡献！！！！

**Comment by MW8023** [comment]
还有一个小问题是那京小超返回日志的时候  奖励京豆显示的是underfinded

**Comment by lxk0301** [comment]
box.js里面设置了四个互助码， 代表的都是别人的农场，是你给别人助力。  不是别人给你助力。你只有4次帮助别人的机会， BoxJs留5个位置干嘛呢？   你帮助第五个肯定是帮助失败。  

额外的奖励是要求 有5个人给你助力。

**Comment by lxk0301** [comment]
> 还有一个小问题是那京小超返回日志的时候 奖励京豆显示的是underfinded

此问题已修复
