### ISSUE TITLE
按照教程来的 但是还是无法自动运行

### ISSUE THREAD

**Issue by misnaya** [lxk0301/scripts#62]
手动点击star可以运行 但是不能自动运行，所有文件均未改动

**Comment by lxk0301** [comment]
教程有写啊。

如果actions出现没有定时执行情况，就修改一下README.md文件(enter键回车添加一个空格)，再提交(或者随便找个文件修改一下)。之后再观察一下，不出意外应该是会执行定时任务了。

**Comment by misnaya** [comment]
> 教程有写啊。
> 
> 如果actions出现没有定时执行情况，就修改一下README.md文件(enter键回车添加一个空格)，再提交(或者随便找个文件修改一下)。之后再观察一下，不出意外应该是会执行定时任务了。

谢谢
