### ISSUE TITLE
请问如何在Jsbox中运行脚本

### ISSUE THREAD

**Issue by Tback1** [lxk0301/scripts#65]
已配置完毕node依赖环境，手工向jdCookie.js写入了cookie

但默认只运行阿里的任务。去掉AlipayManor后，就只运行宠物。直接手工运行超市的jd_blueCoin与jd_superMarket无日志，也无响应

NobyDa的脚本能正常运行，jsbox版本2.11.0（1070）

**Comment by lxk0301** [comment]
就只运行宠物？运行jd_pet.js 吗？运行这个没有问题？

**Comment by Tback1** [comment]
> 就只运行宠物什么意思？运行jd_pet.js 吗？运行这个没有问题？

在jsbox中就只运行文件排序第一位的js文件。运行这个jd_pet.js没问题，输出也正常。

但是运行排序在后边的文件就无效。

尝试过新建一个node项目，只放入
Env.min.js.
jd_blueCoin.js
jd_superMarket.js
jdCookie.js
sendNotify.js
test2.js

点击jd_blueCoin.js编辑，进入编辑模式后，再点击运行，依旧无效

**Comment by lxk0301** [comment]
按理说，jd_pet.js能运行， 其他脚本应该也没问题的。

还有就是我没有jsBox, 不能测试。
