### ISSUE TITLE
github action使用说明(粗略版本)

### ISSUE THREAD

**Issue by MW8023** [lxk0301/scripts#8]
大佬你好，我想问一下怎么使用的创建的actions呢  我每次都用node.js手动请求有点繁琐，我也看到你workflow里写了几个脚本 就是不知道怎么上手

**Comment by lxk0301** [comment]
目前所有的脚本都没兼容多账号，所有只放了几个在workflow里面，也还没写教程， 你可以参考这边 的教程[https://ruicky.me/2020/06/05/jd-sign/](https://ruicky.me/2020/06/05/jd-sign/)

注意几个地方就行，
第一：其中Secrets里面添加 JD_COOKIE的时候。 多账号的cookie， 使用&隔开，比如ck1&ck2&ck3

第二：上面教程里面的推送服务。 这边也还没弄。你可以不用再Secrets里面添加push_key

第三：cron时间是按国际标准时间来的， 和北京时间不同，里面写16点才表示背景时间0点，具体可参考下面两个链接写cron

[参考链接一](https://datetime360.com/cn/utc-beijing-time/)

[参考链接二](http://www.timebie.com/cn/universalbeijing.php)


另外农场和萌宠等助力脚本还没翻到workflow里面， 因为涉及到助力， 还没做好多账号的兼容。
你如果单个账号，可fork过去后，自己新建农场等脚本的workflow。

**Comment by MW8023** [comment]
谢谢 大佬的分享  现在唯一止住我脚步的是无法触发你的actions

**Comment by lxk0301** [comment]
> 谢谢 大佬的分享 现在唯一止住我脚步的是无法触发你的actions

等cron时间到了, 就会自动触发, 或者你自己修改cron, 改成一分钟一次, 然后等着看效果 ,有效果了, 再改回来.

**Comment by DoveBoy** [comment]
> > 谢谢 大佬的分享 现在唯一止住我脚步的是无法触发你的actions
> 
> 等cron时间到了, 就会自动触发, 或者你自己修改cron, 改成一分钟一次, 然后等着看效果 ,有效果了, 再改回来.

开发者可以加个说明，即时触发测试github action可以修改自己fork后的文件，修改readme.md文件最简单，回车加个空行再保存就行了，github action此时会立即触发，然后去action下看看运行结果

**Comment by LawrenceYep** [comment]
你好，我想请教一下，fork后开启了actions，修改自己fork后的readme.md保存提交后，返回actions查看并没有触发，看不见任何action记录，是什么原因呢？

**Comment by MW8023** [comment]
> 你好，我想请教一下，fork后开启了actions，修改自己fork后的readme.md保存提交后，返回actions查看并没有触发，看不见任何action记录，是什么原因呢？

无需担心  我也没有触发  不过定时任务开始得时候会自动触发

**Comment by lxk0301** [comment]
> 你好，我想请教一下，fork后开启了actions，修改自己fork后的readme.md保存提交后，返回actions查看并没有触发，看不见任何action记录，是什么原因呢？

@LawrenceYep  因为他说的（修改自己fork后的readme.md保存提交） 是有条件的。 即提交触发。 目前我yml里面没有添加这个，不然我每次提交代码都会触发一次。

**Comment by LawrenceYep** [comment]
谢谢两位的回答，刚刚修改cron测试了下，已经成功触发。

**Comment by LawrenceYep** [comment]
@lxk0301 还有个小问题想请教一下，就是如果需要使用server酱的通知功能，在secrets中添加PUSH_KEY后是否也要到yml文件中的env添加？

**Comment by lxk0301** [comment]
> @lxk0301 还有个小问题想请教一下，就是如果需要使用server酱的通知功能，在secrets中添加PUSH_KEY后是否也要到yml文件中的env添加？

@LawrenceYep   对， 要的 这边是我忘记添加上去了。
![image](https://user-images.githubusercontent.com/21308593/90714044-5cbea500-e2d9-11ea-9a27-38ed3813bb65.png)

**Comment by Kailic** [comment]
我fork了以后，star之后能运行。但是Actions到时间不自动执行，这是什么情况呢~

**Comment by lxk0301** [comment]
> 我fork了以后，star之后能运行。但是Actions到时间不自动执行，这是什么情况呢~

你删掉这个文件试试看

github/workflows/jd_818.yml

等你反馈

**Comment by Kailic** [comment]
> > 我fork了以后，star之后能运行。但是Actions到时间不自动执行，这是什么情况呢~
> 
> 你删掉这个文件试试看
> 
> .github/workflows/jd_818.yml
> 
> 等你反馈

我删除后，现在自动运行了宠汪汪

**Comment by Kailic** [comment]
> > 我fork了以后，star之后能运行。但是Actions到时间不自动执行，这是什么情况呢~
> 
> 你删掉这个文件试试看
> 
> .github/workflows/jd_818.yml
> 
> 等你反馈

删除掉那个文件以后，自动运行了宠汪汪，过了几分钟又自动运行了喂食。我感觉现在应该是能自己运行了。
