### ISSUE TITLE
❌ 东东农场, 失败! 原因: Error: EROFS: read-only file system, open '/var/user/box.dat'!

### ISSUE THREAD

**Issue by 2320142695** [lxk0301/scripts#87]
部署到腾讯云后提示:`❌ 东东农场, 失败! 原因: Error: EROFS: read-only file system, open '/var/user/box.dat'!`
这一步操作是做什么的，如果是记录日志等一些无关紧要的东西的话，我就忽略了。

**Comment by lxk0301** [comment]
用的是腾讯云函数是吧？
腾讯云函数只有读取文件的权限。没有写入文件的权限，所以报错。你如果要使用。把脚本里面有关$.setdata()的删掉吧

**Comment by 2320142695** [comment]
@lxk0301 是腾讯云函数，这一块的功能是做什么的呐？

**Comment by lxk0301** [comment]
存储数据到缓存。主要是记录你给谁助力过。你删掉也可。

**Comment by 2320142695** [comment]
@lxk0301 好的，谢谢
