### ISSUE TITLE
$getdata 的使用，蓝币兑换京豆，jd_blueCoin.js

### ISSUE THREAD

**Issue by 2320142695** [lxk0301/scripts#88]
```php
'use strict';
exports.main_handler = async (event, context) => {
    require('jd_blueCoin');
};
```
有没有方法在上面的代码中改变`jd_blueCoin.js`里的`coinToBeans`值，本人对js不是特别的懂

**Comment by lxk0301** [comment]
这里写的很明白，把数字0改成1000或者1-20

let coinToBeans = $.getdata('coinToBeans') * 1 || 0; //兑换多少数量的京豆（1-20之间，或者1000），0默认兑换不兑换，如需兑换把0改成1-20之间的数字或者1000即可

**Comment by 2320142695** [comment]
@lxk0301 这个知道，我想如何不改变`jd_blueCoin.js`里面的代码，通过其他另类的方式传入`coinToBeans`的值

**Comment by lxk0301** [comment]
你用的是自己的vps或者云函数。那么目前没有办法

**Comment by 2320142695** [comment]
@lxk0301 
![image](https://user-images.githubusercontent.com/34790068/95444655-a1d58e00-0990-11eb-9e4c-484a80d60b72.png)
![image](https://user-images.githubusercontent.com/34790068/95444680-aa2dc900-0990-11eb-8b74-d807b9422da2.png)

哈哈哈，阅读完Env类后，新建一个`box.dat`文件在里面写入json格式的字符串就行了

**Comment by lxk0301** [comment]
这个方法也是可以。但是你这是腾讯云函数的话 它只有读取文件的权限。没有写入权限
