### ISSUE TITLE
建议屏蔽jd_fruit.js东东农场的使用雨滴换豆卡

### ISSUE THREAD

**Issue by iwshw888** [lxk0301/scripts#89]
实际用雨滴换京东 跟浇水对比起来，换京豆反而还是亏的，还不如浇水

**Comment by lxk0301** [comment]
计算过。换豆和换12块钱红包 是一样的。
但是红包寿命短

**Comment by lxk0301** [comment]
浇水600次得一个12块钱的红包，600次水需要消耗6000g水滴=12红包（1200京豆）

目前100g水滴=20京豆。

自己再计算一下吧。

还有换豆活动也是国庆限时活动，明天就恢复继续浇水了。
