### ISSUE TITLE
 This scheduled workflow is disabled because scheduled workflows are disabled by default in forks.

### ISSUE THREAD

**Issue by thu-zhanghl** [lxk0301/scripts#91]
![image](https://user-images.githubusercontent.com/38646369/95585505-eab14380-0a71-11eb-95dd-5e9bbd6f2076.png)
<br>
### 问题： 

- **默认 Fork 分支的 workflow 被禁用，如上图。**

### 尝试

- **❌ star 自己的 Repository 无法触发 Actions**
- **❌ 修改 README 并推送更改，无法触发 Actions**
- **✅需要一个一个手动 Enable**

有人遇到这样的问题吗？😡，请问怎么触发全部的 Actions Workflow 运行?

**Comment by MisterGlasses** [comment]
我今天fork另一个项目时也是提示这个，手动enable了。

**Comment by lxk0301** [comment]
这个问题倒是第一次遇到 你解决了？

**Comment by MisterGlasses** [comment]
> 这个问题倒是第一次遇到 你解决了？

我是按图上提示点了enable

**Comment by thu-zhanghl** [comment]
> 这个问题倒是第一次遇到 你解决了？

**官方文档中的说明：**
- https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/disabling-and-enabling-a-workflow
![image](https://user-images.githubusercontent.com/38646369/95644467-669aa280-0ae9-11eb-8d0b-cfd2f82c48b4.png)


1. 没有发现有触发所有 Workflow 的设置

2. **解决办法**：克隆仓库到本地→修改 .github 文件夹→提交→✅触发 Actions

**Comment by lxk0301** [comment]
解决办法：克隆仓库到本地→修改 .github 文件夹→提交→✅触发 Actions

修改 .github 文件夹 ？  这个如何修改？
