### ISSUE TITLE
签到领红包 这个感觉可以搞

### ISSUE THREAD

**Issue by Zhuzhen6** [lxk0301/scripts#93]
10.0复制全部 Http:/JHsU1TTc7KgAqp回APP打开领现金签到领钱Fu:淛￥zDVVR5rNNb%这段話后qu最新版（京ㄇ東）

**Comment by lxk0301** [comment]
库里面有。只能做签到。其他任务做不了。能力不够😂

**Comment by lxk0301** [comment]
不能做的原因。可以参考这个

https://blog.csdn.net/hamy168/article/details/106316807
