### ISSUE TITLE
”京小超兑换奖品、签到“的通知还没有开关，大神能不能忙里抽空给加上😋

### ISSUE THREAD

**Issue by gnod512** [lxk0301/scripts#96]

**Comment by gnod512** [comment]
还有种豆得豆通知也没有开关呢

**Comment by lxk0301** [comment]
> 还有种豆得豆通知也没有开关呢

种豆一周一次， 还想关通知？
那你把几个推送通知的secret全部删掉就得了

**Comment by gnod512** [comment]
> > 还有种豆得豆通知也没有开关呢
> 
> 种豆一周一次， 还想关通知？
> 那你把几个推送通知的secret全部删掉就得了
secret删掉cookie失效就没通知了吧？
京小超兑换奖品和签到“的通知有空做个开关呗，大神辛苦了

**Comment by lxk0301** [comment]
已添加

https://github.com/lxk0301/scripts/commit/93368e83ac2eebfadc34503b254059c7f5c2ab06

**Comment by gnod512** [comment]
> 已添加
> 
> [93368e8](https://github.com/lxk0301/scripts/commit/93368e83ac2eebfadc34503b254059c7f5c2ab06)

神一样的大佬👍👍
