### ISSUE TITLE
摇钱树的小问题

### ISSUE THREAD

**Issue by wanthigh** [lxk0301/scripts#97]
昨天开始，app的摇钱树就白屏了（搞了4个号，都一样，有的号提示我暂时无法参加该活动），调用js也没反应了，这是为什么

**Comment by lxk0301** [comment]
这种问题脚本解决不了 , 

自身账号或者网络环境的原因.我这边好好的.

你先看看你手动进去APP摇钱树能不能进去吧.

**Comment by wanthigh** [comment]
进去也不行了。。只能问问客服了
